# coding: utf-8
"""
Source of truth for the LearnDeutsch vocabulary.

This is the ONE place the German <-> Chinese word lists live. `gen_assets.py`
reads this module to produce:
  * the per-group Chinese glyph atlases (resources/images/han_*.png)
  * the generated C data (src/c/vocab_gen.c)
  * the resource list in package.json

Edit the lists, re-run `python tools/gen_assets.py`, rebuild. Nothing else
needs touching.

Decks are grouped into difficulty TIERS (the menu is two levels: pick a tier,
then a deck). Each deck names its tier with the "tier" key. Keep the existing
decks in their current order and never reorder them: a deck's position in
GROUPS is its save slot for best-scores, so reordering shuffles saved progress.
Append new decks at the end (their tier decides where they appear in the menu).

Each card is a tuple:  (german, chinese, english, gender)
  german  : the German word/phrase (nouns include their article, e.g. "das Brot")
  chinese : the Chinese translation (Simplified)
  english : a small English gloss shown as an extra hint
  gender  : "" none, "m" der (blue), "f" die (pink), "n" das (green)
            used only to colour-code the article as a learning aid.
"""

# Difficulty tiers, easiest first. `id` is referenced by each deck's "tier".
TIERS = [
    {"id": "beginner",     "de": "Anfänger",        "zh": "初级", "en": "Beginner",     "accent": "Green"},
    {"id": "elementary",   "de": "Grundstufe",         "zh": "基础", "en": "Elementary",   "accent": "VividCerulean"},
    {"id": "intermediate", "de": "Mittelstufe",        "zh": "中级", "en": "Intermediate", "accent": "Orange"},
    {"id": "advanced",     "de": "Fortgeschritten", "zh": "高级", "en": "Advanced",     "accent": "BrilliantRose"},
]

GROUPS = [
    # ===================== TIER 1 · Beginner =============================
    {
        "key": "greet", "res": "HAN_GREET", "tier": "beginner",
        "de": "Erste Worte", "zh": "入门", "en": "First Words",
        "accent": "Yellow", "icon": "wave",
        "cards": [
            ("Hallo",          "你好",        "hello",            ""),
            ("Tschüss",   "再见",        "bye",              ""),
            ("Danke",          "谢谢",        "thank you",        ""),
            ("Bitte",          "请",              "please",           ""),
            ("Gern geschehen", "不客气",  "you're welcome",   ""),
            ("Ja",             "是",              "yes",              ""),
            ("Nein",           "不",              "no",               ""),
            ("Entschuldigung", "对不起",  "sorry",            ""),
            ("Guten Morgen",   "早上好",  "good morning",     ""),
            ("Guten Abend",    "晚上好",  "good evening",     ""),
            ("Gute Nacht",     "晚安",        "good night",       ""),
            ("Wie geht's?",    "你好吗",  "how are you?",     ""),
            ("Danke schön","非常感谢","thanks a lot", ""),
            ("Willkommen",     "欢迎",        "welcome",          ""),
            ("Prost",          "干杯",        "cheers",           ""),
            ("Bis bald",       "回头见",  "see you soon",     ""),
            ("Genau",          "没错",        "exactly",          ""),
            ("Wie bitte?",     "你说什么","pardon?",          ""),
        ],
    },
    {
        "key": "num", "res": "HAN_NUM", "tier": "beginner",
        "de": "Zahlen", "zh": "数字", "en": "Numbers",
        "accent": "VividCerulean", "icon": "num",
        "cards": [
            ("null",     "零",        "zero",      ""),
            ("eins",     "一",        "one",       ""),
            ("zwei",     "二",        "two",       ""),
            ("drei",     "三",        "three",     ""),
            ("vier",     "四",        "four",      ""),
            ("fünf",  "五",      "five",      ""),
            ("sechs",    "六",        "six",       ""),
            ("sieben",   "七",        "seven",     ""),
            ("acht",     "八",        "eight",     ""),
            ("neun",     "九",        "nine",      ""),
            ("zehn",     "十",        "ten",       ""),
            ("elf",      "十一",  "eleven",    ""),
            ("zwölf", "十二",  "twelve",    ""),
            ("zwanzig",  "二十",  "twenty",    ""),
            ("dreissig","三十",  "thirty",    ""),
            ("hundert",  "一百",  "hundred",   ""),
            ("tausend",  "一千",  "thousand",  ""),
        ],
    },
    {
        "key": "people", "res": "HAN_PEOPLE", "tier": "beginner",
        "de": "Menschen", "zh": "人", "en": "People",
        "accent": "BrilliantRose", "icon": "people",
        "cards": [
            ("ich",            "我",          "I",          ""),
            ("du",             "你",          "you",        ""),
            ("er",             "他",          "he",         ""),
            ("sie",            "她",          "she",        ""),
            ("wir",            "我们",    "we",         ""),
            ("der Mann",       "男人",    "man",        "m"),
            ("die Frau",       "女人",    "woman",      "f"),
            ("das Kind",       "孩子",    "child",      "n"),
            ("der Junge",      "男孩",    "boy",        "m"),
            ("das Mädchen", "女孩",    "girl",       "n"),
            ("die Mutter",     "妈妈",    "mother",     "f"),
            ("der Vater",      "爸爸",    "father",     "m"),
            ("die Schwester",  "姐姐",    "sister",     "f"),
            ("der Bruder",     "哥哥",    "brother",    "m"),
            ("der Freund",     "朋友",    "friend",     "m"),
            ("die Familie",    "家人",    "family",     "f"),
            ("der Name",       "名字",    "name",       "m"),
            ("das Baby",       "宝宝",    "baby",       "n"),
        ],
    },
    {
        "key": "food", "res": "HAN_FOOD", "tier": "beginner",
        "de": "Essen & Trinken", "zh": "饮食", "en": "Food & Drink",
        "accent": "Orange", "icon": "cup",
        "cards": [
            ("das Wasser",  "水",          "water",     "n"),
            ("das Brot",    "面包",    "bread",     "n"),
            ("der Kaffee",  "咖啡",    "coffee",    "m"),
            ("der Tee",     "茶",          "tea",       "m"),
            ("das Bier",    "啤酒",    "beer",      "n"),
            ("der Apfel",   "苹果",    "apple",     "m"),
            ("der Reis",    "米饭",    "rice",      "m"),
            ("das Fleisch", "肉",          "meat",      "n"),
            ("das Ei",      "鸡蛋",    "egg",       "n"),
            ("die Milch",   "牛奶",    "milk",      "f"),
            ("der Fisch",   "鱼",          "fish",      "m"),
            ("das Gemüse","蔬菜", "vegetable", "n"),
            ("das Obst",    "水果",    "fruit",     "n"),
            ("der Zucker",  "糖",          "sugar",     "m"),
            ("die Suppe",   "汤",          "soup",      "f"),
            ("essen",       "吃",          "to eat",    ""),
            ("trinken",     "喝",          "to drink",  ""),
            ("lecker",      "好吃",    "tasty",     ""),
            ("hungrig",     "饿",          "hungry",    ""),
            ("durstig",     "渴",          "thirsty",   ""),
        ],
    },
    {
        "key": "daily", "res": "HAN_DAILY", "tier": "beginner",
        "de": "Alltag", "zh": "日常", "en": "Everyday",
        "accent": "Green", "icon": "sun",
        "cards": [
            ("sein",      "是",          "to be",      ""),
            ("haben",     "有",          "to have",    ""),
            ("gehen",     "去",          "to go",      ""),
            ("kommen",    "来",          "to come",    ""),
            ("machen",    "做",          "to do",      ""),
            ("sprechen",  "说",          "to speak",   ""),
            ("lernen",    "学习",    "to learn",   ""),
            ("lieben",    "爱",          "to love",    ""),
            ("sehen",     "看",          "to see",     ""),
            ("wohnen",    "住",          "to live",    ""),
            ("schlafen",  "睡觉",    "to sleep",   ""),
            ("arbeiten",  "工作",    "to work",    ""),
            ("spielen",   "玩",          "to play",    ""),
            ("heute",     "今天",    "today",      ""),
            ("morgen",    "明天",    "tomorrow",   ""),
            ("gestern",   "昨天",    "yesterday",  ""),
            ("gut",       "好",          "good",       ""),
            ("schlecht",  "不好",    "bad",        ""),
            ("gross",   "大",          "big",        ""),
            ("klein",     "小",          "small",      ""),
            ("die Zeit",  "时间",    "time",       "f"),
        ],
    },
    {
        "key": "phrase", "res": "HAN_PHRASE", "tier": "beginner",
        "de": "Sätze", "zh": "句子", "en": "Phrases",
        "accent": "Purple", "icon": "speech",
        "cards": [
            ("Ich liebe dich",     "我爱你",                  "I love you",        ""),
            ("Wie heisst du?", "你叫什么",            "what's your name?", ""),
            ("Ich heisse ...", "我叫",                        "my name is ...",    ""),
            ("Ich verstehe nicht", "我不明白",            "I don't understand",""),
            ("Sprichst du Englisch?","你会说英语吗","do you speak English?",""),
            ("Wo ist die Toilette?","厕所在哪里",     "where is the toilet?",""),
            ("Wie viel kostet das?","这个多少钱",     "how much is this?", ""),
            ("Ich möchte ...","我想要",                  "I would like ...",  ""),
            ("Freut mich",         "很高兴认识你","nice to meet you",  ""),
            ("Ich komme aus ...",  "我来自",                  "I come from ...",   ""),
            ("Ich bin müde",  "我累了",                  "I am tired",        ""),
            ("Guten Appetit",      "请慢用",                  "enjoy your meal",   ""),
            ("Bis morgen",         "明天见",                  "see you tomorrow",  ""),
            ("Alles Gute",         "一切顺利",            "all the best",      ""),
            ("Keine Ahnung",       "不知道",                  "no idea",           ""),
            ("Kein Problem",       "没问题",                  "no problem",        ""),
            ("Ich weiss nicht", "我不知道",            "I don't know",      ""),
            ("Was ist das?",       "这是什么",            "what is that?",     ""),
        ],
    },

    # ===================== TIER 2 · Elementary ===========================
    {
        "key": "color", "res": "HAN_COLOR", "tier": "elementary",
        "de": "Farben", "zh": "颜色", "en": "Colours",
        "accent": "Magenta", "icon": "palette",
        "cards": [
            ("rot",        "红色",    "red",     ""),
            ("blau",       "蓝色",    "blue",    ""),
            ("grün",    "绿色",    "green",   ""),
            ("gelb",       "黄色",    "yellow",  ""),
            ("schwarz",    "黑色",    "black",   ""),
            ("weiss",    "白色",    "white",   ""),
            ("orange",     "橙色",    "orange",  ""),
            ("lila",       "紫色",    "purple",  ""),
            ("rosa",       "粉色",    "pink",    ""),
            ("braun",      "棕色",    "brown",   ""),
            ("grau",       "灰色",    "grey",    ""),
            ("die Farbe",  "颜色",    "colour",  "f"),
            ("hell",       "浅",          "light",   ""),
            ("dunkel",     "深",          "dark",    ""),
        ],
    },
    {
        "key": "body", "res": "HAN_BODY", "tier": "elementary",
        "de": "Körper", "zh": "身体", "en": "Body",
        "accent": "Folly", "icon": "people",
        "cards": [
            ("der Kopf",   "头",          "head",     "m"),
            ("das Auge",   "眼睛",    "eye",      "n"),
            ("die Nase",   "鼻子",    "nose",     "f"),
            ("der Mund",   "嘴",          "mouth",    "m"),
            ("das Ohr",    "耳朵",    "ear",      "n"),
            ("die Hand",   "手",          "hand",     "f"),
            ("der Fuss",  "脚",          "foot",     "m"),
            ("das Bein",   "腿",          "leg",      "n"),
            ("der Arm",    "手臂",    "arm",      "m"),
            ("der Bauch",  "肚子",    "belly",    "m"),
            ("das Haar",   "头发",    "hair",     "n"),
            ("der Zahn",   "牙齿",    "tooth",    "m"),
            ("das Herz",   "心",          "heart",    "n"),
            ("das Gesicht","脸",          "face",     "n"),
            ("die Schulter",  "肩膀",    "shoulder",  "f"),
            ("der Rücken", "背",          "back",      "m"),
            ("der Hals",      "脖子",    "neck",      "m"),
            ("die Brust",     "胸",          "chest",     "f"),
            ("der Finger",    "手指",    "finger",    "m"),
            ("das Knie",      "膝盖",    "knee",      "n"),
            ("die Zunge",     "舌头",    "tongue",    "f"),
            ("die Augenbraue","眉毛",    "eyebrow",   "f"),
        ],
    },
    {
        "key": "animal", "res": "HAN_ANIMAL", "tier": "elementary",
        "de": "Tiere", "zh": "动物", "en": "Animals",
        "accent": "ChromeYellow", "icon": "paw",
        "cards": [
            ("der Hund",     "狗",          "dog",      "m"),
            ("die Katze",    "猫",          "cat",      "f"),
            ("der Vogel",    "鸟",          "bird",     "m"),
            ("das Pferd",    "马",          "horse",    "n"),
            ("die Kuh",      "牛",          "cow",      "f"),
            ("das Schwein",  "猪",          "pig",      "n"),
            ("das Schaf",    "羊",          "sheep",    "n"),
            ("der Hase",     "兔子",    "rabbit",   "m"),
            ("der Bär",   "熊",          "bear",     "m"),
            ("der Tiger",    "老虎",    "tiger",    "m"),
            ("der Affe",     "猴子",    "monkey",   "m"),
            ("die Maus",     "老鼠",    "mouse",    "f"),
            ("der Elefant",  "大象",    "elephant", "m"),
            ("der Löwe",  "狮子",    "lion",     "m"),
            ("das Tier",     "动物",    "animal",   "n"),
        ],
    },
    {
        "key": "clothes", "res": "HAN_CLOTHES", "tier": "elementary",
        "de": "Kleidung", "zh": "衣服", "en": "Clothes",
        "accent": "Cyan", "icon": "shirt",
        "cards": [
            ("das Hemd",     "衬衫",    "shirt",    "n"),
            ("die Hose",     "裤子",    "trousers", "f"),
            ("der Schuh",    "鞋",          "shoe",     "m"),
            ("die Jacke",    "夹克",    "jacket",   "f"),
            ("der Hut",      "帽子",    "hat",      "m"),
            ("das Kleid",    "连衣裙","dress",    "n"),
            ("der Rock",     "裙子",    "skirt",    "m"),
            ("die Socke",    "袜子",    "sock",     "f"),
            ("der Mantel",   "大衣",    "coat",     "m"),
            ("der Pullover", "毛衣",    "sweater",  "m"),
            ("die Brille",   "眼镜",    "glasses",  "f"),
            ("die Tasche",   "包",          "bag",      "f"),
            ("die Kleidung", "衣服",    "clothing", "f"),
            ("das T-Shirt",  "T恤",          "T-shirt",  "n"),
            ("die Shorts",   "短裤",    "shorts",   "f"),
            ("die Jeans",    "牛仔裤","jeans",    "f"),
            ("die Mütze","帽子",    "cap",      "f"),
            ("der Schal",    "围巾",    "scarf",    "m"),
            ("der Gürtel","皮带",    "belt",     "m"),
            ("der Handschuh","手套",    "glove",    "m"),
            ("der Stiefel",  "靴子",    "boot",     "m"),
            ("die Unterwäsche","内衣","underwear","f"),
        ],
    },
    {
        "key": "home", "res": "HAN_HOME", "tier": "elementary",
        "de": "Zuhause", "zh": "家", "en": "Home",
        "accent": "SpringBud", "icon": "house",
        "cards": [
            ("das Haus",      "房子",    "house",    "n"),
            ("die Wohnung",   "公寓",    "flat",     "f"),
            ("die Tür",    "门",          "door",     "f"),
            ("das Fenster",   "窗户",    "window",   "n"),
            ("der Tisch",     "桌子",    "table",    "m"),
            ("der Stuhl",     "椅子",    "chair",    "m"),
            ("das Bett",      "床",          "bed",      "n"),
            ("die Küche",  "厨房",    "kitchen",  "f"),
            ("das Bad",       "浴室",    "bathroom", "n"),
            ("das Zimmer",    "房间",    "room",     "n"),
            ("die Lampe",     "灯",          "lamp",     "f"),
            ("der Schlüssel","钥匙",  "key",      "m"),
            ("das Sofa",      "沙发",    "sofa",     "n"),
        ],
    },
    {
        "key": "time", "res": "HAN_TIME", "tier": "elementary",
        "de": "Zeit & Tag", "zh": "时间", "en": "Time & Day",
        "accent": "MintGreen", "icon": "clock",
        "cards": [
            ("der Tag",     "天",          "day",      "m"),
            ("die Woche",   "星期",    "week",     "f"),
            ("der Monat",   "月",          "month",    "m"),
            ("das Jahr",    "年",          "year",     "n"),
            ("die Stunde",  "小时",    "hour",     "f"),
            ("die Minute",  "分钟",    "minute",   "f"),
            ("die Uhr",     "钟",          "clock",    "f"),
            ("Montag",      "星期一","Monday",   ""),
            ("Dienstag",    "星期二","Tuesday",  ""),
            ("Mittwoch",    "星期三","Wednesday",""),
            ("Donnerstag",  "星期四","Thursday", ""),
            ("Freitag",     "星期五","Friday",   ""),
            ("Samstag",     "星期六","Saturday", ""),
            ("Sonntag",     "星期日","Sunday",   ""),
            ("jetzt",       "现在",    "now",      ""),
            ("früh",     "早",          "early",    ""),
            ("spät",     "晚",          "late",     ""),
        ],
    },
    {
        "key": "season", "res": "HAN_SEASON", "tier": "elementary",
        "de": "Jahreszeiten", "zh": "季节", "en": "Seasons & Nature",
        "accent": "SpringBud", "icon": "leaf",
        "cards": [
            ("der Frühling","春天",    "spring",   "m"),
            ("der Sommer",     "夏天",    "summer",   "m"),
            ("der Herbst",     "秋天",    "autumn",   "m"),
            ("der Winter",     "冬天",    "winter",   "m"),
            ("die Sonne",      "太阳",    "sun",      "f"),
            ("der Mond",       "月亮",    "moon",     "m"),
            ("der Stern",      "星星",    "star",     "m"),
            ("der Wald",       "森林",    "forest",   "m"),
            ("der Strand",     "海滩",    "beach",    "m"),
            ("die Insel",      "岛",          "island",   "f"),
            ("die Erde",       "地球",    "earth",    "f"),
            ("die Welt",       "世界",    "world",    "f"),
            ("die Natur",      "自然",    "nature",   "f"),
            ("das Gras",       "草",          "grass",    "n"),
        ],
    },
    {
        "key": "hobby", "res": "HAN_HOBBY", "tier": "elementary",
        "de": "Hobbys & Sport", "zh": "爱好", "en": "Hobbies & Sport",
        "accent": "BrilliantRose", "icon": "ball",
        "cards": [
            ("die Musik",      "音乐",    "music",      "f"),
            ("der Sport",      "运动",    "sport",      "m"),
            ("der Fussball", "足球",    "football",   "m"),
            ("das Spiel",      "游戏",    "game",       "n"),
            ("der Film",       "电影",    "film",       "m"),
            ("das Lied",       "歌",          "song",       "n"),
            ("tanzen",         "跳舞",    "to dance",   ""),
            ("singen",         "唱歌",    "to sing",    ""),
            ("schwimmen",      "游泳",    "to swim",    ""),
            ("malen",          "画画",    "to paint",   ""),
            ("fotografieren",  "拍照",    "to photograph",""),
            ("das Konzert",    "音乐会","concert",    "n"),
            ("die Party",      "聚会",    "party",      "f"),
            ("das Hobby",      "爱好",    "hobby",      "n"),
            ("lesen",          "看书",    "to read",        ""),
            ("fernsehen",      "看电视","to watch TV",    ""),
            ("Musik hören", "听音乐","to listen to music",""),
            ("Klavier spielen","弹钢琴","to play piano",  ""),
            ("Basketball spielen","打篮球","to play basketball",""),
            ("Schach spielen", "下棋",    "to play chess",  ""),
            ("reiten",         "骑马",    "to ride a horse",""),
            ("Videospiele spielen","玩游戏","to play video games",""),
        ],
    },
    {
        "key": "date", "res": "HAN_DATE", "tier": "elementary",
        "de": "Datum & Monate", "zh": "日期", "en": "Dates & Months",
        "accent": "VividCerulean", "icon": "calendar",
        "cards": [
            ("Januar",         "一月",            "January",   ""),
            ("Februar",        "二月",            "February",  ""),
            ("März",        "三月",            "March",     ""),
            ("April",          "四月",            "April",     ""),
            ("Mai",            "五月",            "May",       ""),
            ("Juni",           "六月",            "June",      ""),
            ("Juli",           "七月",            "July",      ""),
            ("August",         "八月",            "August",    ""),
            ("September",      "九月",            "September", ""),
            ("Oktober",        "十月",            "October",   ""),
            ("November",       "十一月",      "November",  ""),
            ("Dezember",       "十二月",      "December",  ""),
            ("das Datum",      "日期",            "date",      "n"),
            ("der Geburtstag", "生日",            "birthday",  "m"),
        ],
    },

    # ===================== TIER 3 · Intermediate =========================
    {
        "key": "weather", "res": "HAN_WEATHER", "tier": "intermediate",
        "de": "Wetter", "zh": "天气", "en": "Weather",
        "accent": "PictonBlue", "icon": "cloud",
        "cards": [
            ("das Wetter",  "天气",    "weather", "n"),
            ("der Regen",   "雨",          "rain",    "m"),
            ("der Schnee",  "雪",          "snow",    "m"),
            ("der Wind",    "风",          "wind",    "m"),
            ("die Wolke",   "云",          "cloud",   "f"),
            ("der Himmel",  "天空",    "sky",     "m"),
            ("der Nebel",   "雾",          "fog",     "m"),
            ("warm",        "暖和",    "warm",    ""),
            ("kalt",        "冷",          "cold",    ""),
            ("heiss",     "热",          "hot",     ""),
            ("nass",        "湿",          "wet",     ""),
            ("trocken",     "干",          "dry",     ""),
            ("sonnig",      "晴朗",    "sunny",   ""),
            ("windig",      "有风",    "windy",   ""),
        ],
    },
    {
        "key": "travel", "res": "HAN_TRAVEL", "tier": "intermediate",
        "de": "Stadt & Reisen", "zh": "旅行", "en": "City & Travel",
        "accent": "Rajah", "icon": "plane",
        "cards": [
            ("die Stadt",     "城市",    "city",     "f"),
            ("das Dorf",      "村庄",    "village",  "n"),
            ("das Auto",      "汽车",    "car",      "n"),
            ("der Zug",       "火车",    "train",    "m"),
            ("der Bus",       "公交车","bus",      "m"),
            ("das Flugzeug",  "飞机",    "plane",    "n"),
            ("der Bahnhof",   "火车站","station",  "m"),
            ("der Flughafen", "机场",    "airport",  "m"),
            ("das Hotel",     "酒店",    "hotel",    "n"),
            ("die Strasse", "街道",    "street",   "f"),
            ("die Karte",     "地图",    "map",      "f"),
            ("der Pass",      "护照",    "passport", "m"),
            ("links",         "左",          "left",     ""),
            ("rechts",        "右",          "right",    ""),
            ("geradeaus",     "直走",    "straight", ""),
        ],
    },
    {
        "key": "feeling", "res": "HAN_FEELING", "tier": "intermediate",
        "de": "Gefühle", "zh": "感觉", "en": "Feelings",
        "accent": "BrilliantRose", "icon": "heart",
        "cards": [
            ("glücklich","开心",    "happy",    ""),
            ("traurig",     "难过",    "sad",      ""),
            ("müde",     "累",          "tired",    ""),
            ("krank",       "生病",    "sick",     ""),
            ("wütend",   "生气",    "angry",    ""),
            ("schön",    "美",          "beautiful",""),
            ("hässlich", "丑",          "ugly",     ""),
            ("neu",         "新",          "new",      ""),
            ("alt",         "老",          "old",      ""),
            ("jung",        "年轻",    "young",    ""),
            ("reich",       "富",          "rich",     ""),
            ("arm",         "穷",          "poor",     ""),
            ("stark",       "强",          "strong",   ""),
            ("schwach",     "弱",          "weak",     ""),
            ("einfach",     "简单",    "easy",     ""),
            ("schwer",      "难",          "hard",     ""),
        ],
    },
    {
        "key": "work", "res": "HAN_WORK", "tier": "intermediate",
        "de": "Arbeit & Schule", "zh": "工作", "en": "Work & School",
        "accent": "KellyGreen", "icon": "book",
        "cards": [
            ("die Arbeit",   "工作",    "work",     "f"),
            ("die Schule",   "学校",    "school",   "f"),
            ("der Lehrer",   "老师",    "teacher",  "m"),
            ("der Schüler","学生",  "pupil",    "m"),
            ("das Buch",     "书",          "book",     "n"),
            ("der Stift",    "笔",          "pen",      "m"),
            ("das Papier",   "纸",          "paper",    "n"),
            ("der Computer", "电脑",    "computer", "m"),
            ("das Büro",  "办公室","office",   "n"),
            ("der Chef",     "老板",    "boss",     "m"),
            ("der Arzt",     "医生",    "doctor",   "m"),
            ("die Frage",    "问题",    "question", "f"),
            ("die Antwort",  "答案",    "answer",   "f"),
            ("das Telefon",  "电话",    "phone",    "n"),
        ],
    },
    {
        "key": "verb2", "res": "HAN_VERB2", "tier": "intermediate",
        "de": "Verben 2", "zh": "动词", "en": "More Verbs",
        "accent": "Cyan", "icon": "sun",
        "cards": [
            ("denken",     "想",          "to think",      ""),
            ("wissen",     "知道",    "to know",       ""),
            ("verstehen",  "明白",    "to understand", ""),
            ("fragen",     "问",          "to ask",        ""),
            ("antworten",  "回答",    "to answer",     ""),
            ("helfen",     "帮助",    "to help",       ""),
            ("brauchen",   "需要",    "to need",       ""),
            ("suchen",     "找",          "to look for",   ""),
            ("öffnen",  "打开",    "to open",       ""),
            ("schliessen","关",        "to close",      ""),
            ("beginnen",   "开始",    "to begin",      ""),
            ("warten",     "等",          "to wait",       ""),
            ("fahren",     "开车",    "to drive",      ""),
            ("kaufen",     "买",          "to buy",        ""),
            ("geben",      "给",          "to give",       ""),
            ("bringen",    "带来",    "to bring",      ""),
        ],
    },
    {
        "key": "shop", "res": "HAN_SHOP", "tier": "intermediate",
        "de": "Einkaufen & Geld", "zh": "购物", "en": "Shopping & Money",
        "accent": "Melon", "icon": "bag",
        "cards": [
            ("das Geld",       "钱",          "money",      "n"),
            ("der Euro",       "欧元",    "euro",       "m"),
            ("der Preis",      "价格",    "price",      "m"),
            ("teuer",          "贵",          "expensive",  ""),
            ("billig",         "便宜",    "cheap",      ""),
            ("bezahlen",       "付钱",    "to pay",     ""),
            ("kosten",         "花费",    "to cost",    ""),
            ("der Laden",      "商店",    "shop",       "m"),
            ("der Markt",      "市场",    "market",     "m"),
            ("der Supermarkt", "超市",    "supermarket","m"),
            ("die Rechnung",   "账单",    "bill",       "f"),
            ("das Geschäft","生意",  "business",   "n"),
        ],
    },
    {
        "key": "tech", "res": "HAN_TECH", "tier": "intermediate",
        "de": "Technik", "zh": "科技", "en": "Technology",
        "accent": "VividCerulean", "icon": "phone",
        "cards": [
            ("das Handy",      "手机",        "mobile phone","n"),
            ("der Laptop",     "笔记本",  "laptop",      "m"),
            ("das Internet",   "网络",        "internet",    "n"),
            ("die E-Mail",     "电子邮件","email",       "f"),
            ("die App",        "应用",        "app",         "f"),
            ("der Bildschirm", "屏幕",        "screen",      "m"),
            ("das Passwort",   "密码",        "password",    "n"),
            ("die Tastatur",   "键盘",        "keyboard",    "f"),
            ("die Kopfhörer","耳机",      "headphones",  "f"),
            ("der Drucker",    "打印机",  "printer",     "m"),
            ("die Datei",      "文件",        "file",        "f"),
            ("das Foto",       "照片",        "photo",       "n"),
            ("das Video",      "视频",        "video",       "n"),
        ],
    },
    {
        "key": "kitchen", "res": "HAN_KITCHEN", "tier": "intermediate",
        "de": "In der Küche", "zh": "厨房", "en": "In the Kitchen",
        "accent": "ChromeYellow", "icon": "fork",
        "cards": [
            ("kochen",        "做饭",    "to cook",   ""),
            ("backen",        "烤",          "to bake",   ""),
            ("schneiden",     "切",          "to cut",    ""),
            ("der Herd",      "炉子",    "stove",     "m"),
            ("der Backofen",  "烤箱",    "oven",      "m"),
            ("der Kühlschrank","冰箱","fridge",    "m"),
            ("der Teller",    "盘子",    "plate",     "m"),
            ("die Tasse",     "杯子",    "cup",       "f"),
            ("das Glas",      "玻璃杯","glass",     "n"),
            ("der Topf",      "锅",          "pot",       "m"),
            ("die Pfanne",    "平底锅","pan",       "f"),
            ("das Salz",      "盐",          "salt",      "n"),
            ("der Pfeffer",   "胡椒",    "pepper",    "m"),
            ("die Butter",    "黄油",    "butter",    "f"),
        ],
    },
    {
        "key": "transport", "res": "HAN_TRANSPORT", "tier": "intermediate",
        "de": "Verkehr & Weg", "zh": "交通", "en": "Traffic & Way",
        "accent": "Orange", "icon": "car",
        "cards": [
            ("das Fahrrad",      "自行车",      "bicycle",      "n"),
            ("die U-Bahn",       "地铁",            "subway",       "f"),
            ("die Strassenbahn","有轨电车","tram",         "f"),
            ("das Schiff",       "船",                  "ship",         "n"),
            ("das Motorrad",     "摩托车",      "motorbike",    "n"),
            ("das Taxi",         "出租车",      "taxi",         "n"),
            ("die Haltestelle",  "车站",            "stop",         "f"),
            ("die Ampel",        "红绿灯",      "traffic light","f"),
            ("die Kreuzung",     "路口",            "crossing",     "f"),
            ("der Stau",         "堵车",            "traffic jam",  "m"),
            ("die Fahrkarte",    "车票",            "ticket",       "f"),
            ("abbiegen",         "拐弯",            "to turn",      ""),
            ("parken",           "停车",            "to park",      ""),
            ("weit",             "远",                  "far",          ""),
            ("nah",              "近",                  "near",         ""),
        ],
    },

    # ===================== TIER 4 · Advanced =============================
    {
        "key": "restaurant", "res": "HAN_RESTAURANT", "tier": "advanced",
        "de": "Im Restaurant", "zh": "餐厅", "en": "At the Restaurant",
        "accent": "Orange", "icon": "fork",
        "cards": [
            ("das Restaurant",        "餐厅",            "restaurant",    "n"),
            ("die Speisekarte, bitte","请给我菜单",  "menu, please",  ""),
            ("Ich möchte bestellen","我想点餐",      "I'd like to order",""),
            ("Was empfehlen Sie?",    "你推荐什么",  "what do you recommend?",""),
            ("Die Rechnung, bitte",   "请结账",          "the bill, please",""),
            ("Es schmeckt gut",       "很好吃",          "it tastes good",""),
            ("Ich bin satt",          "我饱了",          "I am full",     ""),
            ("der Kellner",           "服务员",      "waiter",        "m"),
            ("das Trinkgeld",         "小费",            "tip",           "n"),
            ("die Gabel",             "叉子",            "fork",          "f"),
            ("der Löffel",         "勺子",            "spoon",         "m"),
            ("das Messer",            "刀",                  "knife",         "n"),
            ("Zum Wohl!",             "祝健康",          "to your health!",""),
        ],
    },
    {
        "key": "health", "res": "HAN_HEALTH", "tier": "advanced",
        "de": "Beim Arzt", "zh": "看医生", "en": "At the Doctor",
        "accent": "Red", "icon": "plus",
        "cards": [
            ("Mir geht es nicht gut", "我不舒服",      "I don't feel well",""),
            ("Ich bin krank",         "我生病了",      "I am sick",     ""),
            ("Ich habe Kopfschmerzen","我头疼",          "I have a headache",""),
            ("Ich habe Fieber",       "我发烧",          "I have a fever",""),
            ("das Krankenhaus",       "医院",            "hospital",      "n"),
            ("die Apotheke",          "药店",            "pharmacy",      "f"),
            ("die Medizin",           "药",                  "medicine",      "f"),
            ("der Schmerz",           "疼痛",            "pain",          "m"),
            ("gesund",                "健康",            "healthy",       ""),
            ("Gute Besserung",        "早日康复",  "get well soon", ""),
            ("Ich bin allergisch",    "我过敏",          "I'm allergic",  ""),
            ("Ich brauche einen Arzt","我需要医生",  "I need a doctor",""),
        ],
    },
    {
        "key": "phrase2", "res": "HAN_PHRASE2", "tier": "advanced",
        "de": "Sätze 2", "zh": "会话", "en": "Phrases 2",
        "accent": "Magenta", "icon": "speech",
        "cards": [
            ("Können Sie mir helfen?","你能帮我吗",        "can you help me?",""),
            ("Wie spät ist es?",   "现在几点",            "what time is it?",""),
            ("Was bedeutet das?",      "这是什么意思",  "what does that mean?",""),
            ("Langsamer, bitte",       "请慢一点",            "slower, please",""),
            ("Wiederholen Sie bitte",  "请再说一遍",        "please repeat", ""),
            ("Einen Moment, bitte",    "请稍等",                  "one moment, please",""),
            ("Ich habe eine Frage",    "我有一个问题",  "I have a question",""),
            ("Stimmt das?",            "对吗",                    "is that right?",""),
            ("Natürlich",           "当然",                    "of course",     ""),
            ("Vielleicht",             "也许",                    "maybe",         ""),
            ("Ich glaube ja",          "我想是的",            "I think so",    ""),
            ("Wo wohnst du?",          "你住在哪",            "where do you live?",""),
            ("Ich brauche Hilfe",      "我需要帮助",        "I need help",   ""),
            ("Viel Glück",          "祝你好运",            "good luck",     ""),
        ],
    },
    {
        "key": "idiom", "res": "HAN_IDIOM", "tier": "advanced",
        "de": "Redewendungen", "zh": "常用语", "en": "Expressions",
        "accent": "VividCerulean", "icon": "speech",
        "cards": [
            ("Viel Spass",          "玩得开心",        "have fun",        ""),
            ("Mach's gut",            "保重",                "take care",       ""),
            ("Pass auf!",             "小心",                "watch out!",      ""),
            ("Keine Sorge",           "别担心",          "no worries",      ""),
            ("Macht nichts",          "没关系",          "never mind",      ""),
            ("Schade",                "真可惜",          "what a pity",     ""),
            ("Glückwunsch",        "恭喜",                "congratulations", ""),
            ("Frohe Weihnachten",     "圣诞快乐",      "merry Christmas", ""),
            ("Alles Gute zum Geburtstag","生日快乐", "happy birthday",  ""),
            ("Gute Reise",            "一路平安",      "have a good trip",""),
            ("Viel Erfolg",           "祝你成功",      "much success",    ""),
            ("Bis dann",              "到时见",          "see you then",    ""),
        ],
    },
    {
        "key": "office", "res": "HAN_OFFICE", "tier": "advanced",
        "de": "Im Büro", "zh": "办公", "en": "At the Office",
        "accent": "KellyGreen", "icon": "book",
        "cards": [
            ("die Besprechung", "会议",        "meeting",  "f"),
            ("der Termin",      "预约",        "appointment","m"),
            ("der Kollege",     "同事",        "colleague","m"),
            ("der Vertrag",     "合同",        "contract", "m"),
            ("das Projekt",     "项目",        "project",  "n"),
            ("die Aufgabe",     "任务",        "task",     "f"),
            ("die Frist",       "截止日期","deadline", "f"),
            ("der Kunde",       "客户",        "customer", "m"),
            ("der Bericht",     "报告",        "report",   "m"),
            ("das Ziel",        "目标",        "goal",     "n"),
            ("der Plan",        "计划",        "plan",     "m"),
            ("die Idee",        "主意",        "idea",     "f"),
            ("wichtig",         "重要",        "important",""),
            ("beschäftigt",  "忙",              "busy",     ""),
        ],
    },
    {
        "key": "opinion", "res": "HAN_OPINION", "tier": "advanced",
        "de": "Meinung", "zh": "看法", "en": "Opinions",
        "accent": "Purple", "icon": "speech",
        "cards": [
            ("Ich denke, dass ...",    "我想",              "I think that ...",  ""),
            ("Ich glaube, dass ...",   "我相信",        "I believe that ...",""),
            ("Meiner Meinung nach",    "在我看来",  "in my opinion",     ""),
            ("Ich finde das gut",      "我觉得好",  "I like that",       ""),
            ("Ich stimme zu",          "我同意",        "I agree",           ""),
            ("Das stimmt",             "对",                  "that's right",      ""),
            ("Ich bin anderer Meinung","我不同意",  "I disagree",        ""),
            ("Das sehe ich anders",    "我看法不同","I see it differently",""),
            ("Wirklich?",              "真的吗",        "really?",           ""),
            ("Es ist mir egal",        "我无所谓",  "I don't mind",      ""),
            ("Ich bin nicht sicher",   "我不确定",  "I'm not sure",      ""),
            ("Was denkst du?",         "你怎么想",  "what do you think?",""),
        ],
    },
    {
        "key": "emergency", "res": "HAN_EMERGENCY", "tier": "advanced",
        "de": "Notfall", "zh": "紧急", "en": "Emergency",
        "accent": "Red", "icon": "warning",
        "cards": [
            ("Hilfe!",                  "救命",            "help!",         ""),
            ("die Polizei",             "警察",            "police",        "f"),
            ("der Krankenwagen",        "救护车",      "ambulance",     "m"),
            ("der Unfall",              "事故",            "accident",      "m"),
            ("das Feuer",               "火",                  "fire",          "n"),
            ("die Gefahr",              "危险",            "danger",        "f"),
            ("Vorsicht!",               "当心",            "careful!",      ""),
            ("Es ist dringend",         "很紧急",          "it's urgent",   ""),
            ("Rufen Sie die Polizei",   "请叫警察",      "call the police",""),
            ("Rufen Sie einen Krankenwagen","请叫救护车","call an ambulance",""),
            ("Ich habe mich verlaufen", "我迷路了",      "I'm lost",      ""),
            ("Ich habe meinen Pass verloren","我护照丢了","I lost my passport",""),
        ],
    },

    # --- decks built from the children's vocabulary book (curated) -------
    {
        "key": "country", "res": "HAN_COUNTRY", "tier": "elementary",
        "de": "Länder & Sprachen", "zh": "国家", "en": "Countries & Languages",
        "accent": "VividCerulean", "icon": "globe",
        "cards": [
            ("Deutschland",   "德国",        "Germany",            ""),
            ("Deutsch",       "德语",        "German (language)",  ""),
            ("die Schweiz",   "瑞士",        "Switzerland",        "f"),
            ("China",         "中国",        "China",              ""),
            ("Chinesisch",    "汉语",        "Chinese (language)", ""),
            ("Frankreich",    "法国",        "France",             ""),
            ("Französisch","法语",        "French",             ""),
            ("Japan",         "日本",        "Japan",              ""),
            ("Japanisch",     "日语",        "Japanese",           ""),
            ("Russland",      "俄罗斯",  "Russia",             ""),
            ("Russisch",      "俄语",        "Russian",            ""),
            ("die USA",       "美国",        "the USA",            "f"),
            ("Englisch",      "英语",        "English",            ""),
            ("Spanisch",      "西班牙语","Spanish",            ""),
            ("Italienisch",   "意大利语","Italian",            ""),
            ("Mexiko",        "墨西哥",  "Mexico",             ""),
        ],
    },
    {
        "key": "city", "res": "HAN_CITY", "tier": "intermediate",
        "de": "In der Stadt", "zh": "城市", "en": "In the City",
        "accent": "Rajah", "icon": "building",
        "cards": [
            ("das Kino",          "电影院",  "cinema",         "n"),
            ("die Post",          "邮局",        "post office",    "f"),
            ("die Bank",          "银行",        "bank",           "f"),
            ("die Feuerwache",    "消防站",  "fire station",   "f"),
            ("die Polizeiwache",  "公安局",  "police station", "f"),
            ("der Kindergarten",  "幼儿园",  "kindergarten",   "m"),
            ("die Tankstelle",    "加油站",  "petrol station", "f"),
            ("die Fabrik",        "工厂",        "factory",        "f"),
            ("die Kirche",        "教堂",        "church",         "f"),
            ("das Museum",        "博物馆",  "museum",         "n"),
            ("der Park",          "公园",        "park",           "m"),
            ("die Bibliothek",    "图书馆",  "library",        "f"),
            ("der Zoo",           "动物园",  "zoo",            "m"),
        ],
    },
    {
        "key": "play", "res": "HAN_PLAY", "tier": "elementary",
        "de": "Spielplatz", "zh": "游乐场", "en": "Playground",
        "accent": "BrilliantRose", "icon": "ball",
        "cards": [
            ("das Versteckspiel", "捉迷藏",  "hide-and-seek",     "n"),
            ("schaukeln",         "荡秋千",  "to swing",          ""),
            ("die Schaukel",      "秋千",        "swing",             "f"),
            ("Seil springen",     "跳绳",        "to skip rope",      ""),
            ("rutschen",          "滑滑梯",  "to go down a slide",""),
            ("die Wippe",         "跷跷板",  "seesaw",            "f"),
            ("das Puzzle",        "拼图",        "jigsaw puzzle",     "n"),
            ("das Frisbee",       "飞盘",        "frisbee",           "n"),
            ("die Wasserpistole", "水枪",        "water gun",         "f"),
            ("die Seifenblase",   "泡泡",        "soap bubble",       "f"),
            ("im Sand spielen",   "玩沙",        "to play in the sand",""),
            ("Skateboard fahren", "玩滑板",  "to skateboard",     ""),
            ("Rad fahren",        "骑车",        "to ride a bike",    ""),
            ("Himmel und Hölle","跳房子",  "hopscotch",         ""),
        ],
    },
    {
        "key": "move", "res": "HAN_MOVE", "tier": "intermediate",
        "de": "Bewegung", "zh": "动作", "en": "Movement",
        "accent": "Green", "icon": "run",
        "cards": [
            ("springen",   "跳",          "to jump",      ""),
            ("sitzen",     "坐",          "to sit",       ""),
            ("stehen",     "站",          "to stand",     ""),
            ("rennen",     "跑",          "to run",       ""),
            ("schieben",   "推",          "to push",      ""),
            ("ziehen",     "拉",          "to pull",      ""),
            ("klettern",   "爬",          "to climb",     ""),
            ("liegen",     "躺",          "to lie down",  ""),
            ("hocken",     "蹲",          "to crouch",    ""),
            ("werfen",     "扔",          "to throw",     ""),
            ("fangen",     "抓",          "to catch",     ""),
            ("berühren","摸",          "to touch",     ""),
            ("beissen",    "咬",          "to bite",      ""),
            ("halten",     "拿",          "to hold",      ""),
        ],
    },
    {
        "key": "look", "res": "HAN_LOOK", "tier": "intermediate",
        "de": "Aussehen", "zh": "外貌", "en": "Appearance",
        "accent": "Magenta", "icon": "people",
        "cards": [
            ("gross",          "高",          "tall",           ""),
            ("klein",          "矮",          "short (height)", ""),
            ("dick",           "胖",          "fat",            ""),
            ("dünn",        "瘦",          "thin",           ""),
            ("hübsch",      "漂亮",    "pretty",         ""),
            ("süss",        "可爱",    "cute",           ""),
            ("attraktiv",      "帅",          "handsome",       ""),
            ("kurze Haare",    "短发",    "short hair",     ""),
            ("lange Haare",    "长发",    "long hair",      ""),
            ("lockige Haare",  "卷发",    "curly hair",     ""),
            ("glatte Haare",   "直发",    "straight hair",  ""),
            ("die Zöpfe",   "辫子",    "braids",         "f"),
            ("die Figur",      "身材",    "figure",         "f"),
            ("das Aussehen",   "长相",    "appearance",     "n"),
        ],
    },
    {
        "key": "pet", "res": "HAN_PET", "tier": "elementary",
        "de": "Haustiere", "zh": "宠物", "en": "Pets",
        "accent": "ChromeYellow", "icon": "paw",
        "cards": [
            ("das Haustier",    "宠物",    "pet",        "n"),
            ("der Papagei",     "鹦鹉",    "parrot",     "m"),
            ("die Schildkröte","乌龟",  "turtle",     "f"),
            ("der Goldfisch",   "金鱼",    "goldfish",   "m"),
            ("der Flügel",   "翅膀",    "wing",       "m"),
            ("der Vogelkäfig","鸟笼",  "birdcage",   "m"),
            ("die Hundehütte","狗窝",  "doghouse",   "f"),
            ("der Tierarzt",    "兽医",    "vet",        "m"),
            ("das Aquarium",    "鱼缸",    "aquarium",   "n"),
            ("der Schwanz",     "尾巴",    "tail",       "m"),
            ("füttern",      "喂",          "to feed",    ""),
            ("baden",           "洗澡",    "to bathe",   ""),
            ("trainieren",      "训练",    "to train",   ""),
            ("streicheln",      "抚摸",    "to stroke",  ""),
        ],
    },
    {
        "key": "room", "res": "HAN_ROOM", "tier": "elementary",
        "de": "Zimmer & Möbel", "zh": "房间", "en": "Rooms & Furniture",
        "accent": "SpringBud", "icon": "house",
        "cards": [
            ("das Schlafzimmer", "卧室",    "bedroom",         "n"),
            ("das Wohnzimmer",   "客厅",    "living room",     "n"),
            ("das Esszimmer",    "饭厅",    "dining room",     "n"),
            ("der Balkon",       "阳台",    "balcony",         "m"),
            ("der Garten",       "花园",    "garden",          "m"),
            ("die Garage",       "车库",    "garage",          "f"),
            ("der Hof",          "院子",    "courtyard",       "m"),
            ("die Treppe",       "楼梯",    "stairs",          "f"),
            ("die Waschmaschine","洗衣机","washing machine", "f"),
            ("die Klimaanlage",  "空调",    "air conditioner", "f"),
            ("der Fernseher",    "电视",    "television",      "m"),
            ("die Fernbedienung","遥控器","remote control",  "f"),
            ("das Kissen",       "枕头",    "pillow",          "n"),
            ("die Schublade",    "抽屉",    "drawer",          "f"),
            ("das Schloss",      "锁",          "lock",            "n"),
        ],
    },
    {
        "key": "thing", "res": "HAN_THING", "tier": "intermediate",
        "de": "Dinge im Haus", "zh": "物品", "en": "Things at Home",
        "accent": "MintGreen", "icon": "box",
        "cards": [
            ("der Schlafanzug",  "睡衣",    "pyjamas",      "m"),
            ("das Bücherregal","书架",  "bookshelf",    "n"),
            ("die Steckdose",    "插座",    "socket",       "f"),
            ("der Stecker",      "插头",    "plug",         "m"),
            ("das Kabel",        "电线",    "cable",        "n"),
            ("die Bettdecke",    "被子",    "duvet",        "f"),
            ("die Decke",        "毯子",    "blanket",      "f"),
            ("der Wecker",       "闹钟",    "alarm clock",  "m"),
            ("die Hausschuhe",   "拖鞋",    "slippers",     "f"),
            ("der Teppich",      "地毯",    "carpet",       "m"),
            ("der Regenschirm",  "伞",          "umbrella",     "m"),
            ("die Zeitschrift",  "杂志",    "magazine",     "f"),
            ("das Spielzeug",    "玩具",    "toy",          "n"),
            ("die Puppe",        "布娃娃","doll",         "f"),
            ("der Teddybär",  "玩具熊","teddy bear",   "m"),
            ("der Roboter",      "机器人","robot",        "m"),
        ],
    },
]

# ---------------------------------------------------------------------------
# Bilingual UI text. Every Chinese string the C code draws OUTSIDE of a card
# answer must be listed here, so its glyphs land in the always-loaded UI atlas.
# (Deck names and tier names are collected automatically.)
# ---------------------------------------------------------------------------
UI_STRINGS = {
    "TITLE":     "学德语",      # Learn German
    "DE":        "德",                  # "German" tag for the direction chip
    "ZH":        "中",                  # "Chinese" tag for the direction chip
    "FLIP":      "翻",                  # flip
    "DONE":      "完成",            # done / complete
    "LEARNED":   "学会",            # learned
    "AGAIN":     "再来",            # again
    "MENU":      "菜单",            # menu
    "STATS":     "统计",            # statistics
    "WORDS":     "词",                  # words (counter unit)
    "DECKS":     "组",                  # decks/groups (counter unit)
}

# Random praise (shown on a correct answer) and nudges (on a miss).
UI_PRAISE = ["太棒了", "真厉害", "好极了"]   # awesome / impressive / great
UI_NUDGE  = ["差一点", "再试试", "加油"]         # almost / try again / keep going
