# coding: utf-8
"""
Source of truth for the LearnDeutsch vocabulary.

This is the ONE place the German <-> Chinese word lists live. `gen_assets.py`
reads this module to produce:
  * the per-group Chinese glyph atlases (resources/images/han_*.png)
  * the generated C data (src/c/vocab_gen.c)
  * the resource list in package.json

Edit the lists, re-run `python tools/gen_assets.py`, rebuild. Nothing else
needs touching.

Decks are grouped into difficulty TIERS (the menu is two levels: pick a tier,
then a deck). Each deck names its tier with the "tier" key. Keep the existing
decks in their current order and never reorder them: a deck's position in
GROUPS is its save slot for best-scores, so reordering shuffles saved progress.
Append new decks at the end (their tier decides where they appear in the menu).

Each card is a tuple:  (german, chinese, english, gender)
  german  : the German word/phrase (nouns include their article, e.g. "das Brot")
  chinese : the Chinese translation (Simplified)
  english : a small English gloss shown as an extra hint
  gender  : "" none, "m" der (blue), "f" die (pink), "n" das (green)
            used only to colour-code the article as a learning aid.
"""

# Difficulty tiers, easiest first. `id` is referenced by each deck's "tier".
TIERS = [
    {"id": "beginner",     "de": "Anfänger",        "zh": "初级", "en": "Beginner",     "accent": "Green"},
    {"id": "elementary",   "de": "Grundstufe",         "zh": "基础", "en": "Elementary",   "accent": "VividCerulean"},
    {"id": "intermediate", "de": "Mittelstufe",        "zh": "中级", "en": "Intermediate", "accent": "Orange"},
    {"id": "advanced",     "de": "Fortgeschritten", "zh": "高级", "en": "Advanced",     "accent": "BrilliantRose"},
]

GROUPS = [
    # ===================== TIER 1 · Beginner =============================
    {
        "key": "greet", "res": "HAN_GREET", "tier": "beginner",
        "de": "Erste Worte", "zh": "入门", "en": "First Words",
        "accent": "Yellow", "icon": "wave",
        "cards": [
            ("Hallo",          "你好",        "hello",            ""),
            ("Tschüss",   "再见",        "bye",              ""),
            ("Danke",          "谢谢",        "thank you",        ""),
            ("Bitte",          "请",              "please",           ""),
            ("Gern geschehen", "不客气",  "you're welcome",   ""),
            ("Ja",             "是",              "yes",              ""),
            ("Nein",           "不",              "no",               ""),
            ("Entschuldigung", "对不起",  "sorry",            ""),
            ("Guten Morgen",   "早上好",  "good morning",     ""),
            ("Guten Abend",    "晚上好",  "good evening",     ""),
            ("Gute Nacht",     "晚安",        "good night",       ""),
            ("Wie geht's?",    "你好吗",  "how are you?",     ""),
            ("Danke schön","非常感谢","thanks a lot", ""),
            ("Willkommen",     "欢迎",        "welcome",          ""),
            ("Prost",          "干杯",        "cheers",           ""),
            ("Bis bald",       "回头见",  "see you soon",     ""),
            ("Genau",          "没错",        "exactly",          ""),
            ("Wie bitte?",     "你说什么","pardon?",          ""),
        ],
    },
    {
        "key": "num", "res": "HAN_NUM", "tier": "beginner",
        "de": "Zahlen", "zh": "数字", "en": "Numbers",
        "accent": "VividCerulean", "icon": "num",
        "cards": [
            ("null",     "零",        "zero",      ""),
            ("eins",     "一",        "one",       ""),
            ("zwei",     "二",        "two",       ""),
            ("drei",     "三",        "three",     ""),
            ("vier",     "四",        "four",      ""),
            ("fünf",  "五",      "five",      ""),
            ("sechs",    "六",        "six",       ""),
            ("sieben",   "七",        "seven",     ""),
            ("acht",     "八",        "eight",     ""),
            ("neun",     "九",        "nine",      ""),
            ("zehn",     "十",        "ten",       ""),
            ("elf",      "十一",  "eleven",    ""),
            ("zwölf", "十二",  "twelve",    ""),
            ("zwanzig",  "二十",  "twenty",    ""),
            ("dreissig","三十",  "thirty",    ""),
            ("hundert",  "一百",  "hundred",   ""),
            ("tausend",  "一千",  "thousand",  ""),
        ],
    },
    {
        "key": "people", "res": "HAN_PEOPLE", "tier": "beginner",
        "de": "Menschen", "zh": "人", "en": "People",
        "accent": "BrilliantRose", "icon": "people",
        "cards": [
            ("ich",            "我",          "I",          ""),
            ("du",             "你",          "you",        ""),
            ("er",             "他",          "he",         ""),
            ("sie",            "她",          "she",        ""),
            ("wir",            "我们",    "we",         ""),
            ("der Mann",       "男人",    "man",        "m"),
            ("die Frau",       "女人",    "woman",      "f"),
            ("das Kind",       "孩子",    "child",      "n"),
            ("der Junge",      "男孩",    "boy",        "m"),
            ("das Mädchen", "女孩",    "girl",       "n"),
            ("die Mutter",     "妈妈",    "mother",     "f"),
            ("der Vater",      "爸爸",    "father",     "m"),
            ("die Schwester",  "姐姐",    "sister",     "f"),
            ("der Bruder",     "哥哥",    "brother",    "m"),
            ("der Freund",     "朋友",    "friend",     "m"),
            ("die Familie",    "家人",    "family",     "f"),
            ("der Name",       "名字",    "name",       "m"),
            ("das Baby",       "宝宝",    "baby",       "n"),
        ],
    },
    {
        "key": "food", "res": "HAN_FOOD", "tier": "beginner",
        "de": "Essen & Trinken", "zh": "饮食", "en": "Food & Drink",
        "accent": "Orange", "icon": "cup",
        "cards": [
            ("das Wasser",  "水",          "water",     "n"),
            ("das Brot",    "面包",    "bread",     "n"),
            ("der Kaffee",  "咖啡",    "coffee",    "m"),
            ("der Tee",     "茶",          "tea",       "m"),
            ("das Bier",    "啤酒",    "beer",      "n"),
            ("der Apfel",   "苹果",    "apple",     "m"),
            ("der Reis",    "米饭",    "rice",      "m"),
            ("das Fleisch", "肉",          "meat",      "n"),
            ("das Ei",      "鸡蛋",    "egg",       "n"),
            ("die Milch",   "牛奶",    "milk",      "f"),
            ("der Fisch",   "鱼",          "fish",      "m"),
            ("das Gemüse","蔬菜", "vegetable", "n"),
            ("das Obst",    "水果",    "fruit",     "n"),
            ("der Zucker",  "糖",          "sugar",     "m"),
            ("die Suppe",   "汤",          "soup",      "f"),
            ("essen",       "吃",          "to eat",    ""),
            ("trinken",     "喝",          "to drink",  ""),
            ("lecker",      "好吃",    "tasty",     ""),
            ("hungrig",     "饿",          "hungry",    ""),
            ("durstig",     "渴",          "thirsty",   ""),
        ],
    },
    {
        "key": "daily", "res": "HAN_DAILY", "tier": "beginner",
        "de": "Alltag", "zh": "日常", "en": "Everyday",
        "accent": "Green", "icon": "sun",
        "cards": [
            ("sein",      "是",          "to be",      ""),
            ("haben",     "有",          "to have",    ""),
            ("gehen",     "去",          "to go",      ""),
            ("kommen",    "来",          "to come",    ""),
            ("machen",    "做",          "to do",      ""),
            ("sprechen",  "说",          "to speak",   ""),
            ("lernen",    "学习",    "to learn",   ""),
            ("lieben",    "爱",          "to love",    ""),
            ("sehen",     "看",          "to see",     ""),
            ("wohnen",    "住",          "to live",    ""),
            ("schlafen",  "睡觉",    "to sleep",   ""),
            ("arbeiten",  "工作",    "to work",    ""),
            ("spielen",   "玩",          "to play",    ""),
            ("heute",     "今天",    "today",      ""),
            ("morgen",    "明天",    "tomorrow",   ""),
            ("gestern",   "昨天",    "yesterday",  ""),
            ("gut",       "好",          "good",       ""),
            ("schlecht",  "不好",    "bad",        ""),
            ("gross",   "大",          "big",        ""),
            ("klein",     "小",          "small",      ""),
            ("die Zeit",  "时间",    "time",       "f"),
        ],
    },
    {
        "key": "phrase", "res": "HAN_PHRASE", "tier": "beginner",
        "de": "Sätze", "zh": "句子", "en": "Phrases",
        "accent": "Purple", "icon": "speech",
        "cards": [
            ("Ich liebe dich",     "我爱你",                  "I love you",        ""),
            ("Wie heisst du?", "你叫什么",            "what's your name?", ""),
            ("Ich heisse ...", "我叫",                        "my name is ...",    ""),
            ("Ich verstehe nicht", "我不明白",            "I don't understand",""),
            ("Sprichst du Englisch?","你会说英语吗","do you speak English?",""),
            ("Wo ist die Toilette?","厕所在哪里",     "where is the toilet?",""),
            ("Wie viel kostet das?","这个多少钱",     "how much is this?", ""),
            ("Ich möchte ...","我想要",                  "I would like ...",  ""),
            ("Freut mich",         "很高兴认识你","nice to meet you",  ""),
            ("Ich komme aus ...",  "我来自",                  "I come from ...",   ""),
            ("Ich bin müde",  "我累了",                  "I am tired",        ""),
            ("Guten Appetit",      "请慢用",                  "enjoy your meal",   ""),
            ("Bis morgen",         "明天见",                  "see you tomorrow",  ""),
            ("Alles Gute",         "一切顺利",            "all the best",      ""),
            ("Keine Ahnung",       "不知道",                  "no idea",           ""),
            ("Kein Problem",       "没问题",                  "no problem",        ""),
            ("Ich weiss nicht", "我不知道",            "I don't know",      ""),
            ("Was ist das?",       "这是什么",            "what is that?",     ""),
        ],
    },

    # ===================== TIER 2 · Elementary ===========================
    {
        "key": "color", "res": "HAN_COLOR", "tier": "elementary",
        "de": "Farben", "zh": "颜色", "en": "Colours",
        "accent": "Magenta", "icon": "palette",
        "cards": [
            ("rot",        "红色",    "red",     ""),
            ("blau",       "蓝色",    "blue",    ""),
            ("grün",    "绿色",    "green",   ""),
            ("gelb",       "黄色",    "yellow",  ""),
            ("schwarz",    "黑色",    "black",   ""),
            ("weiss",    "白色",    "white",   ""),
            ("orange",     "橙色",    "orange",  ""),
            ("lila",       "紫色",    "purple",  ""),
            ("rosa",       "粉色",    "pink",    ""),
            ("braun",      "棕色",    "brown",   ""),
            ("grau",       "灰色",    "grey",    ""),
            ("die Farbe",  "颜色",    "colour",  "f"),
            ("hell",       "浅",          "light",   ""),
            ("dunkel",     "深",          "dark",    ""),
        ],
    },
    {
        "key": "body", "res": "HAN_BODY", "tier": "elementary",
        "de": "Körper", "zh": "身体", "en": "Body",
        "accent": "Folly", "icon": "people",
        "cards": [
            ("der Kopf",   "头",          "head",     "m"),
            ("das Auge",   "眼睛",    "eye",      "n"),
            ("die Nase",   "鼻子",    "nose",     "f"),
            ("der Mund",   "嘴",          "mouth",    "m"),
            ("das Ohr",    "耳朵",    "ear",      "n"),
            ("die Hand",   "手",          "hand",     "f"),
            ("der Fuss",  "脚",          "foot",     "m"),
            ("das Bein",   "腿",          "leg",      "n"),
            ("der Arm",    "手臂",    "arm",      "m"),
            ("der Bauch",  "肚子",    "belly",    "m"),
            ("das Haar",   "头发",    "hair",     "n"),
            ("der Zahn",   "牙齿",    "tooth",    "m"),
            ("das Herz",   "心",          "heart",    "n"),
            ("das Gesicht","脸",          "face",     "n"),
            ("die Schulter",  "肩膀",    "shoulder",  "f"),
            ("der Rücken", "背",          "back",      "m"),
            ("der Hals",      "脖子",    "neck",      "m"),
            ("die Brust",     "胸",          "chest",     "f"),
            ("der Finger",    "手指",    "finger",    "m"),
            ("das Knie",      "膝盖",    "knee",      "n"),
            ("die Zunge",     "舌头",    "tongue",    "f"),
            ("die Augenbraue","眉毛",    "eyebrow",   "f"),
        ],
    },
    {
        "key": "animal", "res": "HAN_ANIMAL", "tier": "elementary",
        "de": "Tiere", "zh": "动物", "en": "Animals",
        "accent": "ChromeYellow", "icon": "paw",
        "cards": [
            ("der Hund",     "狗",          "dog",      "m"),
            ("die Katze",    "猫",          "cat",      "f"),
            ("der Vogel",    "鸟",          "bird",     "m"),
            ("das Pferd",    "马",          "horse",    "n"),
            ("die Kuh",      "牛",          "cow",      "f"),
            ("das Schwein",  "猪",          "pig",      "n"),
            ("das Schaf",    "羊",          "sheep",    "n"),
            ("der Hase",     "兔子",    "rabbit",   "m"),
            ("der Bär",   "熊",          "bear",     "m"),
            ("der Tiger",    "老虎",    "tiger",    "m"),
            ("der Affe",     "猴子",    "monkey",   "m"),
            ("die Maus",     "老鼠",    "mouse",    "f"),
            ("der Elefant",  "大象",    "elephant", "m"),
            ("der Löwe",  "狮子",    "lion",     "m"),
            ("das Tier",     "动物",    "animal",   "n"),
        ],
    },
    {
        "key": "clothes", "res": "HAN_CLOTHES", "tier": "elementary",
        "de": "Kleidung", "zh": "衣服", "en": "Clothes",
        "accent": "Cyan", "icon": "shirt",
        "cards": [
            ("das Hemd",     "衬衫",    "shirt",    "n"),
            ("die Hose",     "裤子",    "trousers", "f"),
            ("der Schuh",    "鞋",          "shoe",     "m"),
            ("die Jacke",    "夹克",    "jacket",   "f"),
            ("der Hut",      "帽子",    "hat",      "m"),
            ("das Kleid",    "连衣裙","dress",    "n"),
            ("der Rock",     "裙子",    "skirt",    "m"),
            ("die Socke",    "袜子",    "sock",     "f"),
            ("der Mantel",   "大衣",    "coat",     "m"),
            ("der Pullover", "毛衣",    "sweater",  "m"),
            ("die Brille",   "眼镜",    "glasses",  "f"),
            ("die Tasche",   "包",          "bag",      "f"),
            ("die Kleidung", "衣服",    "clothing", "f"),
            ("das T-Shirt",  "T恤",          "T-shirt",  "n"),
            ("die Shorts",   "短裤",    "shorts",   "f"),
            ("die Jeans",    "牛仔裤","jeans",    "f"),
            ("die Mütze","帽子",    "cap",      "f"),
            ("der Schal",    "围巾",    "scarf",    "m"),
            ("der Gürtel","皮带",    "belt",     "m"),
            ("der Handschuh","手套",    "glove",    "m"),
            ("der Stiefel",  "靴子",    "boot",     "m"),
            ("die Unterwäsche","内衣","underwear","f"),
        ],
    },
    {
        "key": "home", "res": "HAN_HOME", "tier": "elementary",
        "de": "Zuhause", "zh": "家", "en": "Home",
        "accent": "SpringBud", "icon": "house",
        "cards": [
            ("das Haus",      "房子",    "house",    "n"),
            ("die Wohnung",   "公寓",    "flat",     "f"),
            ("die Tür",    "门",          "door",     "f"),
            ("das Fenster",   "窗户",    "window",   "n"),
            ("der Tisch",     "桌子",    "table",    "m"),
            ("der Stuhl",     "椅子",    "chair",    "m"),
            ("das Bett",      "床",          "bed",      "n"),
            ("die Küche",  "厨房",    "kitchen",  "f"),
            ("das Bad",       "浴室",    "bathroom", "n"),
            ("das Zimmer",    "房间",    "room",     "n"),
            ("die Lampe",     "灯",          "lamp",     "f"),
            ("der Schlüssel","钥匙",  "key",      "m"),
            ("das Sofa",      "沙发",    "sofa",     "n"),
        ],
    },
    {
        "key": "time", "res": "HAN_TIME", "tier": "elementary",
        "de": "Zeit & Tag", "zh": "时间", "en": "Time & Day",
        "accent": "MintGreen", "icon": "clock",
        "cards": [
            ("der Tag",     "天",          "day",      "m"),
            ("die Woche",   "星期",    "week",     "f"),
            ("der Monat",   "月",          "month",    "m"),
            ("das Jahr",    "年",          "year",     "n"),
            ("die Stunde",  "小时",    "hour",     "f"),
            ("die Minute",  "分钟",    "minute",   "f"),
            ("die Uhr",     "钟",          "clock",    "f"),
            ("Montag",      "星期一","Monday",   ""),
            ("Dienstag",    "星期二","Tuesday",  ""),
            ("Mittwoch",    "星期三","Wednesday",""),
            ("Donnerstag",  "星期四","Thursday", ""),
            ("Freitag",     "星期五","Friday",   ""),
            ("Samstag",     "星期六","Saturday", ""),
            ("Sonntag",     "星期日","Sunday",   ""),
            ("jetzt",       "现在",    "now",      ""),
            ("früh",     "早",          "early",    ""),
            ("spät",     "晚",          "late",     ""),
        ],
    },
    {
        "key": "season", "res": "HAN_SEASON", "tier": "elementary",
        "de": "Jahreszeiten", "zh": "季节", "en": "Seasons & Nature",
        "accent": "SpringBud", "icon": "leaf",
        "cards": [
            ("der Frühling","春天",    "spring",   "m"),
            ("der Sommer",     "夏天",    "summer",   "m"),
            ("der Herbst",     "秋天",    "autumn",   "m"),
            ("der Winter",     "冬天",    "winter",   "m"),
            ("die Sonne",      "太阳",    "sun",      "f"),
            ("der Mond",       "月亮",    "moon",     "m"),
            ("der Stern",      "星星",    "star",     "m"),
            ("der Wald",       "森林",    "forest",   "m"),
            ("der Strand",     "海滩",    "beach",    "m"),
            ("die Insel",      "岛",          "island",   "f"),
            ("die Erde",       "地球",    "earth",    "f"),
            ("die Welt",       "世界",    "world",    "f"),
            ("die Natur",      "自然",    "nature",   "f"),
            ("das Gras",       "草",          "grass",    "n"),
        ],
    },
    {
        "key": "hobby", "res": "HAN_HOBBY", "tier": "elementary",
        "de": "Hobbys & Sport", "zh": "爱好", "en": "Hobbies & Sport",
        "accent": "BrilliantRose", "icon": "ball",
        "cards": [
            ("die Musik",      "音乐",    "music",      "f"),
            ("der Sport",      "运动",    "sport",      "m"),
            ("der Fussball", "足球",    "football",   "m"),
            ("das Spiel",      "游戏",    "game",       "n"),
            ("der Film",       "电影",    "film",       "m"),
            ("das Lied",       "歌",          "song",       "n"),
            ("tanzen",         "跳舞",    "to dance",   ""),
            ("singen",         "唱歌",    "to sing",    ""),
            ("schwimmen",      "游泳",    "to swim",    ""),
            ("malen",          "画画",    "to paint",   ""),
            ("fotografieren",  "拍照",    "to photograph",""),
            ("das Konzert",    "音乐会","concert",    "n"),
            ("die Party",      "聚会",    "party",      "f"),
            ("das Hobby",      "爱好",    "hobby",      "n"),
            ("lesen",          "看书",    "to read",        ""),
            ("fernsehen",      "看电视","to watch TV",    ""),
            ("Musik hören", "听音乐","to listen to music",""),
            ("Klavier spielen","弹钢琴","to play piano",  ""),
            ("Basketball spielen","打篮球","to play basketball",""),
            ("Schach spielen", "下棋",    "to play chess",  ""),
            ("reiten",         "骑马",    "to ride a horse",""),
            ("Videospiele spielen","玩游戏","to play video games",""),
        ],
    },
    {
        "key": "date", "res": "HAN_DATE", "tier": "elementary",
        "de": "Datum & Monate", "zh": "日期", "en": "Dates & Months",
        "accent": "VividCerulean", "icon": "calendar",
        "cards": [
            ("Januar",         "一月",            "January",   ""),
            ("Februar",        "二月",            "February",  ""),
            ("März",        "三月",            "March",     ""),
            ("April",          "四月",            "April",     ""),
            ("Mai",            "五月",            "May",       ""),
            ("Juni",           "六月",            "June",      ""),
            ("Juli",           "七月",            "July",      ""),
            ("August",         "八月",            "August",    ""),
            ("September",      "九月",            "September", ""),
            ("Oktober",        "十月",            "October",   ""),
            ("November",       "十一月",      "November",  ""),
            ("Dezember",       "十二月",      "December",  ""),
            ("das Datum",      "日期",            "date",      "n"),
            ("der Geburtstag", "生日",            "birthday",  "m"),
        ],
    },

    # ===================== TIER 3 · Intermediate =========================
    {
        "key": "weather", "res": "HAN_WEATHER", "tier": "intermediate",
        "de": "Wetter", "zh": "天气", "en": "Weather",
        "accent": "PictonBlue", "icon": "cloud",
        "cards": [
            ("das Wetter",  "天气",    "weather", "n"),
            ("der Regen",   "雨",          "rain",    "m"),
            ("der Schnee",  "雪",          "snow",    "m"),
            ("der Wind",    "风",          "wind",    "m"),
            ("die Wolke",   "云",          "cloud",   "f"),
            ("der Himmel",  "天空",    "sky",     "m"),
            ("der Nebel",   "雾",          "fog",     "m"),
            ("warm",        "暖和",    "warm",    ""),
            ("kalt",        "冷",          "cold",    ""),
            ("heiss",     "热",          "hot",     ""),
            ("nass",        "湿",          "wet",     ""),
            ("trocken",     "干",          "dry",     ""),
            ("sonnig",      "晴朗",    "sunny",   ""),
            ("windig",      "有风",    "windy",   ""),
        ],
    },
    {
        "key": "travel", "res": "HAN_TRAVEL", "tier": "intermediate",
        "de": "Stadt & Reisen", "zh": "旅行", "en": "City & Travel",
        "accent": "Rajah", "icon": "plane",
        "cards": [
            ("die Stadt",     "城市",    "city",     "f"),
            ("das Dorf",      "村庄",    "village",  "n"),
            ("das Auto",      "汽车",    "car",      "n"),
            ("der Zug",       "火车",    "train",    "m"),
            ("der Bus",       "公交车","bus",      "m"),
            ("das Flugzeug",  "飞机",    "plane",    "n"),
            ("der Bahnhof",   "火车站","station",  "m"),
            ("der Flughafen", "机场",    "airport",  "m"),
            ("das Hotel",     "酒店",    "hotel",    "n"),
            ("die Strasse", "街道",    "street",   "f"),
            ("die Karte",     "地图",    "map",      "f"),
            ("der Pass",      "护照",    "passport", "m"),
            ("links",         "左",          "left",     ""),
            ("rechts",        "右",          "right",    ""),
            ("geradeaus",     "直走",    "straight", ""),
        ],
    },
    {
        "key": "feeling", "res": "HAN_FEELING", "tier": "intermediate",
        "de": "Gefühle", "zh": "感觉", "en": "Feelings",
        "accent": "BrilliantRose", "icon": "heart",
        "cards": [
            ("glücklich","开心",    "happy",    ""),
            ("traurig",     "难过",    "sad",      ""),
            ("müde",     "累",          "tired",    ""),
            ("krank",       "生病",    "sick",     ""),
            ("wütend",   "生气",    "angry",    ""),
            ("schön",    "美",          "beautiful",""),
            ("hässlich", "丑",          "ugly",     ""),
            ("neu",         "新",          "new",      ""),
            ("alt",         "老",          "old",      ""),
            ("jung",        "年轻",    "young",    ""),
            ("reich",       "富",          "rich",     ""),
            ("arm",         "穷",          "poor",     ""),
            ("stark",       "强",          "strong",   ""),
            ("schwach",     "弱",          "weak",     ""),
            ("einfach",     "简单",    "easy",     ""),
            ("schwer",      "难",          "hard",     ""),
        ],
    },
    {
        "key": "work", "res": "HAN_WORK", "tier": "intermediate",
        "de": "Arbeit & Schule", "zh": "工作", "en": "Work & School",
        "accent": "KellyGreen", "icon": "book",
        "cards": [
            ("die Arbeit",   "工作",    "work",     "f"),
            ("die Schule",   "学校",    "school",   "f"),
            ("der Lehrer",   "老师",    "teacher",  "m"),
            ("der Schüler","学生",  "pupil",    "m"),
            ("das Buch",     "书",          "book",     "n"),
            ("der Stift",    "笔",          "pen",      "m"),
            ("das Papier",   "纸",          "paper",    "n"),
            ("der Computer", "电脑",    "computer", "m"),
            ("das Büro",  "办公室","office",   "n"),
            ("der Chef",     "老板",    "boss",     "m"),
            ("der Arzt",     "医生",    "doctor",   "m"),
            ("die Frage",    "问题",    "question", "f"),
            ("die Antwort",  "答案",    "answer",   "f"),
            ("das Telefon",  "电话",    "phone",    "n"),
        ],
    },
    {
        "key": "verb2", "res": "HAN_VERB2", "tier": "intermediate",
        "de": "Verben 2", "zh": "动词", "en": "More Verbs",
        "accent": "Cyan", "icon": "sun",
        "cards": [
            ("denken",     "想",          "to think",      ""),
            ("wissen",     "知道",    "to know",       ""),
            ("verstehen",  "明白",    "to understand", ""),
            ("fragen",     "问",          "to ask",        ""),
            ("antworten",  "回答",    "to answer",     ""),
            ("helfen",     "帮助",    "to help",       ""),
            ("brauchen",   "需要",    "to need",       ""),
            ("suchen",     "找",          "to look for",   ""),
            ("öffnen",  "打开",    "to open",       ""),
            ("schliessen","关",        "to close",      ""),
            ("beginnen",   "开始",    "to begin",      ""),
            ("warten",     "等",          "to wait",       ""),
            ("fahren",     "开车",    "to drive",      ""),
            ("kaufen",     "买",          "to buy",        ""),
            ("geben",      "给",          "to give",       ""),
            ("bringen",    "带来",    "to bring",      ""),
        ],
    },
    {
        "key": "shop", "res": "HAN_SHOP", "tier": "intermediate",
        "de": "Einkaufen & Geld", "zh": "购物", "en": "Shopping & Money",
        "accent": "Melon", "icon": "bag",
        "cards": [
            ("das Geld",       "钱",          "money",      "n"),
            ("der Euro",       "欧元",    "euro",       "m"),
            ("der Preis",      "价格",    "price",      "m"),
            ("teuer",          "贵",          "expensive",  ""),
            ("billig",         "便宜",    "cheap",      ""),
            ("bezahlen",       "付钱",    "to pay",     ""),
            ("kosten",         "花费",    "to cost",    ""),
            ("der Laden",      "商店",    "shop",       "m"),
            ("der Markt",      "市场",    "market",     "m"),
            ("der Supermarkt", "超市",    "supermarket","m"),
            ("die Rechnung",   "账单",    "bill",       "f"),
            ("das Geschäft","生意",  "business",   "n"),
        ],
    },
    {
        "key": "tech", "res": "HAN_TECH", "tier": "intermediate",
        "de": "Technik", "zh": "科技", "en": "Technology",
        "accent": "VividCerulean", "icon": "phone",
        "cards": [
            ("das Handy",      "手机",        "mobile phone","n"),
            ("der Laptop",     "笔记本",  "laptop",      "m"),
            ("das Internet",   "网络",        "internet",    "n"),
            ("die E-Mail",     "电子邮件","email",       "f"),
            ("die App",        "应用",        "app",         "f"),
            ("der Bildschirm", "屏幕",        "screen",      "m"),
            ("das Passwort",   "密码",        "password",    "n"),
            ("die Tastatur",   "键盘",        "keyboard",    "f"),
            ("die Kopfhörer","耳机",      "headphones",  "f"),
            ("der Drucker",    "打印机",  "printer",     "m"),
            ("die Datei",      "文件",        "file",        "f"),
            ("das Foto",       "照片",        "photo",       "n"),
            ("das Video",      "视频",        "video",       "n"),
        ],
    },
    {
        "key": "kitchen", "res": "HAN_KITCHEN", "tier": "intermediate",
        "de": "In der Küche", "zh": "厨房", "en": "In the Kitchen",
        "accent": "ChromeYellow", "icon": "fork",
        "cards": [
            ("kochen",        "做饭",    "to cook",   ""),
            ("backen",        "烤",          "to bake",   ""),
            ("schneiden",     "切",          "to cut",    ""),
            ("der Herd",      "炉子",    "stove",     "m"),
            ("der Backofen",  "烤箱",    "oven",      "m"),
            ("der Kühlschrank","冰箱","fridge",    "m"),
            ("der Teller",    "盘子",    "plate",     "m"),
            ("die Tasse",     "杯子",    "cup",       "f"),
            ("das Glas",      "玻璃杯","glass",     "n"),
            ("der Topf",      "锅",          "pot",       "m"),
            ("die Pfanne",    "平底锅","pan",       "f"),
            ("das Salz",      "盐",          "salt",      "n"),
            ("der Pfeffer",   "胡椒",    "pepper",    "m"),
            ("die Butter",    "黄油",    "butter",    "f"),
        ],
    },
    {
        "key": "transport", "res": "HAN_TRANSPORT", "tier": "intermediate",
        "de": "Verkehr & Weg", "zh": "交通", "en": "Traffic & Way",
        "accent": "Orange", "icon": "car",
        "cards": [
            ("das Fahrrad",      "自行车",      "bicycle",      "n"),
            ("die U-Bahn",       "地铁",            "subway",       "f"),
            ("die Strassenbahn","有轨电车","tram",         "f"),
            ("das Schiff",       "船",                  "ship",         "n"),
            ("das Motorrad",     "摩托车",      "motorbike",    "n"),
            ("das Taxi",         "出租车",      "taxi",         "n"),
            ("die Haltestelle",  "车站",            "stop",         "f"),
            ("die Ampel",        "红绿灯",      "traffic light","f"),
            ("die Kreuzung",     "路口",            "crossing",     "f"),
            ("der Stau",         "堵车",            "traffic jam",  "m"),
            ("die Fahrkarte",    "车票",            "ticket",       "f"),
            ("abbiegen",         "拐弯",            "to turn",      ""),
            ("parken",           "停车",            "to park",      ""),
            ("weit",             "远",                  "far",          ""),
            ("nah",              "近",                  "near",         ""),
        ],
    },

    # ===================== TIER 4 · Advanced =============================
    {
        "key": "restaurant", "res": "HAN_RESTAURANT", "tier": "advanced",
        "de": "Im Restaurant", "zh": "餐厅", "en": "At the Restaurant",
        "accent": "Orange", "icon": "fork",
        "cards": [
            ("das Restaurant",        "餐厅",            "restaurant",    "n"),
            ("die Speisekarte, bitte","请给我菜单",  "menu, please",  ""),
            ("Ich möchte bestellen","我想点餐",      "I'd like to order",""),
            ("Was empfehlen Sie?",    "你推荐什么",  "what do you recommend?",""),
            ("Die Rechnung, bitte",   "请结账",          "the bill, please",""),
            ("Es schmeckt gut",       "很好吃",          "it tastes good",""),
            ("Ich bin satt",          "我饱了",          "I am full",     ""),
            ("der Kellner",           "服务员",      "waiter",        "m"),
            ("das Trinkgeld",         "小费",            "tip",           "n"),
            ("die Gabel",             "叉子",            "fork",          "f"),
            ("der Löffel",         "勺子",            "spoon",         "m"),
            ("das Messer",            "刀",                  "knife",         "n"),
            ("Zum Wohl!",             "祝健康",          "to your health!",""),
        ],
    },
    {
        "key": "health", "res": "HAN_HEALTH", "tier": "advanced",
        "de": "Beim Arzt", "zh": "看医生", "en": "At the Doctor",
        "accent": "Red", "icon": "plus",
        "cards": [
            ("Mir geht es nicht gut", "我不舒服",      "I don't feel well",""),
            ("Ich bin krank",         "我生病了",      "I am sick",     ""),
            ("Ich habe Kopfschmerzen","我头疼",          "I have a headache",""),
            ("Ich habe Fieber",       "我发烧",          "I have a fever",""),
            ("das Krankenhaus",       "医院",            "hospital",      "n"),
            ("die Apotheke",          "药店",            "pharmacy",      "f"),
            ("die Medizin",           "药",                  "medicine",      "f"),
            ("der Schmerz",           "疼痛",            "pain",          "m"),
            ("gesund",                "健康",            "healthy",       ""),
            ("Gute Besserung",        "早日康复",  "get well soon", ""),
            ("Ich bin allergisch",    "我过敏",          "I'm allergic",  ""),
            ("Ich brauche einen Arzt","我需要医生",  "I need a doctor",""),
        ],
    },
    {
        "key": "phrase2", "res": "HAN_PHRASE2", "tier": "advanced",
        "de": "Sätze 2", "zh": "会话", "en": "Phrases 2",
        "accent": "Magenta", "icon": "speech",
        "cards": [
            ("Können Sie mir helfen?","你能帮我吗",        "can you help me?",""),
            ("Wie spät ist es?",   "现在几点",            "what time is it?",""),
            ("Was bedeutet das?",      "这是什么意思",  "what does that mean?",""),
            ("Langsamer, bitte",       "请慢一点",            "slower, please",""),
            ("Wiederholen Sie bitte",  "请再说一遍",        "please repeat", ""),
            ("Einen Moment, bitte",    "请稍等",                  "one moment, please",""),
            ("Ich habe eine Frage",    "我有一个问题",  "I have a question",""),
            ("Stimmt das?",            "对吗",                    "is that right?",""),
            ("Natürlich",           "当然",                    "of course",     ""),
            ("Vielleicht",             "也许",                    "maybe",         ""),
            ("Ich glaube ja",          "我想是的",            "I think so",    ""),
            ("Wo wohnst du?",          "你住在哪",            "where do you live?",""),
            ("Ich brauche Hilfe",      "我需要帮助",        "I need help",   ""),
            ("Viel Glück",          "祝你好运",            "good luck",     ""),
        ],
    },
    {
        "key": "idiom", "res": "HAN_IDIOM", "tier": "advanced",
        "de": "Redewendungen", "zh": "常用语", "en": "Expressions",
        "accent": "VividCerulean", "icon": "speech",
        "cards": [
            ("Viel Spass",          "玩得开心",        "have fun",        ""),
            ("Mach's gut",            "保重",                "take care",       ""),
            ("Pass auf!",             "小心",                "watch out!",      ""),
            ("Keine Sorge",           "别担心",          "no worries",      ""),
            ("Macht nichts",          "没关系",          "never mind",      ""),
            ("Schade",                "真可惜",          "what a pity",     ""),
            ("Glückwunsch",        "恭喜",                "congratulations", ""),
            ("Frohe Weihnachten",     "圣诞快乐",      "merry Christmas", ""),
            ("Alles Gute zum Geburtstag","生日快乐", "happy birthday",  ""),
            ("Gute Reise",            "一路平安",      "have a good trip",""),
            ("Viel Erfolg",           "祝你成功",      "much success",    ""),
            ("Bis dann",              "到时见",          "see you then",    ""),
        ],
    },
    {
        "key": "office", "res": "HAN_OFFICE", "tier": "advanced",
        "de": "Im Büro", "zh": "办公", "en": "At the Office",
        "accent": "KellyGreen", "icon": "book",
        "cards": [
            ("die Besprechung", "会议",        "meeting",  "f"),
            ("der Termin",      "预约",        "appointment","m"),
            ("der Kollege",     "同事",        "colleague","m"),
            ("der Vertrag",     "合同",        "contract", "m"),
            ("das Projekt",     "项目",        "project",  "n"),
            ("die Aufgabe",     "任务",        "task",     "f"),
            ("die Frist",       "截止日期","deadline", "f"),
            ("der Kunde",       "客户",        "customer", "m"),
            ("der Bericht",     "报告",        "report",   "m"),
            ("das Ziel",        "目标",        "goal",     "n"),
            ("der Plan",        "计划",        "plan",     "m"),
            ("die Idee",        "主意",        "idea",     "f"),
            ("wichtig",         "重要",        "important",""),
            ("beschäftigt",  "忙",              "busy",     ""),
        ],
    },
    {
        "key": "opinion", "res": "HAN_OPINION", "tier": "advanced",
        "de": "Meinung", "zh": "看法", "en": "Opinions",
        "accent": "Purple", "icon": "speech",
        "cards": [
            ("Ich denke, dass ...",    "我想",              "I think that ...",  ""),
            ("Ich glaube, dass ...",   "我相信",        "I believe that ...",""),
            ("Meiner Meinung nach",    "在我看来",  "in my opinion",     ""),
            ("Ich finde das gut",      "我觉得好",  "I like that",       ""),
            ("Ich stimme zu",          "我同意",        "I agree",           ""),
            ("Das stimmt",             "对",                  "that's right",      ""),
            ("Ich bin anderer Meinung","我不同意",  "I disagree",        ""),
            ("Das sehe ich anders",    "我看法不同","I see it differently",""),
            ("Wirklich?",              "真的吗",        "really?",           ""),
            ("Es ist mir egal",        "我无所谓",  "I don't mind",      ""),
            ("Ich bin nicht sicher",   "我不确定",  "I'm not sure",      ""),
            ("Was denkst du?",         "你怎么想",  "what do you think?",""),
        ],
    },
    {
        "key": "emergency", "res": "HAN_EMERGENCY", "tier": "advanced",
        "de": "Notfall", "zh": "紧急", "en": "Emergency",
        "accent": "Red", "icon": "warning",
        "cards": [
            ("Hilfe!",                  "救命",            "help!",         ""),
            ("die Polizei",             "警察",            "police",        "f"),
            ("der Krankenwagen",        "救护车",      "ambulance",     "m"),
            ("der Unfall",              "事故",            "accident",      "m"),
            ("das Feuer",               "火",                  "fire",          "n"),
            ("die Gefahr",              "危险",            "danger",        "f"),
            ("Vorsicht!",               "当心",            "careful!",      ""),
            ("Es ist dringend",         "很紧急",          "it's urgent",   ""),
            ("Rufen Sie die Polizei",   "请叫警察",      "call the police",""),
            ("Rufen Sie einen Krankenwagen","请叫救护车","call an ambulance",""),
            ("Ich habe mich verlaufen", "我迷路了",      "I'm lost",      ""),
            ("Ich habe meinen Pass verloren","我护照丢了","I lost my passport",""),
        ],
    },

    # --- decks built from the children's vocabulary book (curated) -------
    {
        "key": "country", "res": "HAN_COUNTRY", "tier": "elementary",
        "de": "Länder & Sprachen", "zh": "国家", "en": "Countries & Languages",
        "accent": "VividCerulean", "icon": "globe",
        "cards": [
            ("Deutschland",   "德国",        "Germany",            ""),
            ("Deutsch",       "德语",        "German (language)",  ""),
            ("die Schweiz",   "瑞士",        "Switzerland",        "f"),
            ("China",         "中国",        "China",              ""),
            ("Chinesisch",    "汉语",        "Chinese (language)", ""),
            ("Frankreich",    "法国",        "France",             ""),
            ("Französisch","法语",        "French",             ""),
            ("Japan",         "日本",        "Japan",              ""),
            ("Japanisch",     "日语",        "Japanese",           ""),
            ("Russland",      "俄罗斯",  "Russia",             ""),
            ("Russisch",      "俄语",        "Russian",            ""),
            ("die USA",       "美国",        "the USA",            "f"),
            ("Englisch",      "英语",        "English",            ""),
            ("Spanisch",      "西班牙语","Spanish",            ""),
            ("Italienisch",   "意大利语","Italian",            ""),
            ("Mexiko",        "墨西哥",  "Mexico",             ""),
        ],
    },
    {
        "key": "city", "res": "HAN_CITY", "tier": "intermediate",
        "de": "In der Stadt", "zh": "城市", "en": "In the City",
        "accent": "Rajah", "icon": "building",
        "cards": [
            ("das Kino",          "电影院",  "cinema",         "n"),
            ("die Post",          "邮局",        "post office",    "f"),
            ("die Bank",          "银行",        "bank",           "f"),
            ("die Feuerwache",    "消防站",  "fire station",   "f"),
            ("die Polizeiwache",  "公安局",  "police station", "f"),
            ("der Kindergarten",  "幼儿园",  "kindergarten",   "m"),
            ("die Tankstelle",    "加油站",  "petrol station", "f"),
            ("die Fabrik",        "工厂",        "factory",        "f"),
            ("die Kirche",        "教堂",        "church",         "f"),
            ("das Museum",        "博物馆",  "museum",         "n"),
            ("der Park",          "公园",        "park",           "m"),
            ("die Bibliothek",    "图书馆",  "library",        "f"),
            ("der Zoo",           "动物园",  "zoo",            "m"),
        ],
    },
    {
        "key": "play", "res": "HAN_PLAY", "tier": "elementary",
        "de": "Spielplatz", "zh": "游乐场", "en": "Playground",
        "accent": "BrilliantRose", "icon": "ball",
        "cards": [
            ("das Versteckspiel", "捉迷藏",  "hide-and-seek",     "n"),
            ("schaukeln",         "荡秋千",  "to swing",          ""),
            ("die Schaukel",      "秋千",        "swing",             "f"),
            ("Seil springen",     "跳绳",        "to skip rope",      ""),
            ("rutschen",          "滑滑梯",  "to go down a slide",""),
            ("die Wippe",         "跷跷板",  "seesaw",            "f"),
            ("das Puzzle",        "拼图",        "jigsaw puzzle",     "n"),
            ("das Frisbee",       "飞盘",        "frisbee",           "n"),
            ("die Wasserpistole", "水枪",        "water gun",         "f"),
            ("die Seifenblase",   "泡泡",        "soap bubble",       "f"),
            ("im Sand spielen",   "玩沙",        "to play in the sand",""),
            ("Skateboard fahren", "玩滑板",  "to skateboard",     ""),
            ("Rad fahren",        "骑车",        "to ride a bike",    ""),
            ("Himmel und Hölle","跳房子",  "hopscotch",         ""),
        ],
    },
    {
        "key": "move", "res": "HAN_MOVE", "tier": "intermediate",
        "de": "Bewegung", "zh": "动作", "en": "Movement",
        "accent": "Green", "icon": "run",
        "cards": [
            ("springen",   "跳",          "to jump",      ""),
            ("sitzen",     "坐",          "to sit",       ""),
            ("stehen",     "站",          "to stand",     ""),
            ("rennen",     "跑",          "to run",       ""),
            ("schieben",   "推",          "to push",      ""),
            ("ziehen",     "拉",          "to pull",      ""),
            ("klettern",   "爬",          "to climb",     ""),
            ("liegen",     "躺",          "to lie down",  ""),
            ("hocken",     "蹲",          "to crouch",    ""),
            ("werfen",     "扔",          "to throw",     ""),
            ("fangen",     "抓",          "to catch",     ""),
            ("berühren","摸",          "to touch",     ""),
            ("beissen",    "咬",          "to bite",      ""),
            ("halten",     "拿",          "to hold",      ""),
        ],
    },
    {
        "key": "look", "res": "HAN_LOOK", "tier": "intermediate",
        "de": "Aussehen", "zh": "外貌", "en": "Appearance",
        "accent": "Magenta", "icon": "people",
        "cards": [
            ("gross",          "高",          "tall",           ""),
            ("klein",          "矮",          "short (height)", ""),
            ("dick",           "胖",          "fat",            ""),
            ("dünn",        "瘦",          "thin",           ""),
            ("hübsch",      "漂亮",    "pretty",         ""),
            ("süss",        "可爱",    "cute",           ""),
            ("attraktiv",      "帅",          "handsome",       ""),
            ("kurze Haare",    "短发",    "short hair",     ""),
            ("lange Haare",    "长发",    "long hair",      ""),
            ("lockige Haare",  "卷发",    "curly hair",     ""),
            ("glatte Haare",   "直发",    "straight hair",  ""),
            ("die Zöpfe",   "辫子",    "braids",         "f"),
            ("die Figur",      "身材",    "figure",         "f"),
            ("das Aussehen",   "长相",    "appearance",     "n"),
        ],
    },
    {
        "key": "pet", "res": "HAN_PET", "tier": "elementary",
        "de": "Haustiere", "zh": "宠物", "en": "Pets",
        "accent": "ChromeYellow", "icon": "paw",
        "cards": [
            ("das Haustier",    "宠物",    "pet",        "n"),
            ("der Papagei",     "鹦鹉",    "parrot",     "m"),
            ("die Schildkröte","乌龟",  "turtle",     "f"),
            ("der Goldfisch",   "金鱼",    "goldfish",   "m"),
            ("der Flügel",   "翅膀",    "wing",       "m"),
            ("der Vogelkäfig","鸟笼",  "birdcage",   "m"),
            ("die Hundehütte","狗窝",  "doghouse",   "f"),
            ("der Tierarzt",    "兽医",    "vet",        "m"),
            ("das Aquarium",    "鱼缸",    "aquarium",   "n"),
            ("der Schwanz",     "尾巴",    "tail",       "m"),
            ("füttern",      "喂",          "to feed",    ""),
            ("baden",           "洗澡",    "to bathe",   ""),
            ("trainieren",      "训练",    "to train",   ""),
            ("streicheln",      "抚摸",    "to stroke",  ""),
        ],
    },
    {
        "key": "room", "res": "HAN_ROOM", "tier": "elementary",
        "de": "Zimmer & Möbel", "zh": "房间", "en": "Rooms & Furniture",
        "accent": "SpringBud", "icon": "house",
        "cards": [
            ("das Schlafzimmer", "卧室",    "bedroom",         "n"),
            ("das Wohnzimmer",   "客厅",    "living room",     "n"),
            ("das Esszimmer",    "饭厅",    "dining room",     "n"),
            ("der Balkon",       "阳台",    "balcony",         "m"),
            ("der Garten",       "花园",    "garden",          "m"),
            ("die Garage",       "车库",    "garage",          "f"),
            ("der Hof",          "院子",    "courtyard",       "m"),
            ("die Treppe",       "楼梯",    "stairs",          "f"),
            ("die Waschmaschine","洗衣机","washing machine", "f"),
            ("die Klimaanlage",  "空调",    "air conditioner", "f"),
            ("der Fernseher",    "电视",    "television",      "m"),
            ("die Fernbedienung","遥控器","remote control",  "f"),
            ("das Kissen",       "枕头",    "pillow",          "n"),
            ("die Schublade",    "抽屉",    "drawer",          "f"),
            ("das Schloss",      "锁",          "lock",            "n"),
        ],
    },
    {
        "key": "thing", "res": "HAN_THING", "tier": "intermediate",
        "de": "Dinge im Haus", "zh": "物品", "en": "Things at Home",
        "accent": "MintGreen", "icon": "box",
        "cards": [
            ("der Schlafanzug",  "睡衣",    "pyjamas",      "m"),
            ("das Bücherregal","书架",  "bookshelf",    "n"),
            ("die Steckdose",    "插座",    "socket",       "f"),
            ("der Stecker",      "插头",    "plug",         "m"),
            ("das Kabel",        "电线",    "cable",        "n"),
            ("die Bettdecke",    "被子",    "duvet",        "f"),
            ("die Decke",        "毯子",    "blanket",      "f"),
            ("der Wecker",       "闹钟",    "alarm clock",  "m"),
            ("die Hausschuhe",   "拖鞋",    "slippers",     "f"),
            ("der Teppich",      "地毯",    "carpet",       "m"),
            ("der Regenschirm",  "伞",          "umbrella",     "m"),
            ("die Zeitschrift",  "杂志",    "magazine",     "f"),
            ("das Spielzeug",    "玩具",    "toy",          "n"),
            ("die Puppe",        "布娃娃","doll",         "f"),
            ("der Teddybär",  "玩具熊","teddy bear",   "m"),
            ("der Roboter",      "机器人","robot",        "m"),
        ],
    },

    # --- extended vocabulary: 42 more decks that roughly double the word ---
    # --- count, spread across all four tiers (appended, never reordered) ---
    {
        "key": "ask", "res": "HAN_ASK", "tier": "beginner",
        "de": "Fragewörter", "zh": "问句", "en": "Question Words",
        "accent": "Yellow", "icon": "speech",
        "cards": [
            ("wer", "谁", "who", ""),
            ("was", "什么", "what", ""),
            ("wo", "哪里", "where", ""),
            ("wann", "什么时候", "when", ""),
            ("warum", "为什么", "why", ""),
            ("wie", "怎么", "how", ""),
            ("welcher", "哪个", "which", ""),
            ("wie viel", "多少", "how much", ""),
            ("wie viele", "多少", "how many", ""),
            ("wohin", "去哪里", "where to", ""),
            ("woher", "从哪里", "where from", ""),
            ("wieso", "为什么", "how come", ""),
            ("weshalb", "为何", "for what reason", ""),
            ("was für", "什么样的", "what kind of", ""),
        ],
    },
    {
        "key": "verb1", "res": "HAN_VERB1", "tier": "beginner",
        "de": "Verben 1", "zh": "基本", "en": "Basic Verbs",
        "accent": "Green", "icon": "run",
        "cards": [
            ("sagen", "说", "to say", ""),
            ("nehmen", "拿", "to take", ""),
            ("finden", "找到", "to find", ""),
            ("bleiben", "停留", "to stay", ""),
            ("legen", "平放", "to lay", ""),
            ("stellen", "摆放", "to put", ""),
            ("tragen", "携带", "to carry", ""),
            ("rufen", "呼喊", "to call", ""),
            ("zeigen", "展示", "to show", ""),
            ("hören", "听", "to hear", ""),
            ("fühlen", "感觉", "to feel", ""),
            ("glauben", "相信", "to believe", ""),
            ("hoffen", "希望", "to hope", ""),
            ("feiern", "庆祝", "to celebrate", ""),
            ("holen", "取来", "to fetch", ""),
            ("packen", "打包", "to pack", ""),
        ],
    },
    {
        "key": "opposite", "res": "HAN_OPPOSITE", "tier": "beginner",
        "de": "Gegensätze", "zh": "反义", "en": "Opposites",
        "accent": "VividCerulean", "icon": "box",
        "cards": [
            ("auf", "开", "open", ""),
            ("zu", "关", "closed", ""),
            ("viel", "多", "much", ""),
            ("wenig", "少", "little", ""),
            ("alles", "一切", "everything", ""),
            ("nichts", "什么都没有", "nothing", ""),
            ("immer", "总是", "always", ""),
            ("nie", "从不", "never", ""),
            ("richtig", "正确", "correct", ""),
            ("falsch", "错误", "wrong", ""),
            ("leer", "空", "empty", ""),
            ("voll", "满", "full", ""),
            ("offen", "开着的", "open", ""),
            ("geschlossen", "关着的", "closed", ""),
            ("laut", "大声", "loud", ""),
            ("leise", "安静", "quiet", ""),
        ],
    },
    {
        "key": "word", "res": "HAN_WORD", "tier": "beginner",
        "de": "Kleine Wörter", "zh": "虚词", "en": "Little Words",
        "accent": "Purple", "icon": "book",
        "cards": [
            ("und", "和", "and", ""),
            ("oder", "或者", "or", ""),
            ("aber", "但是", "but", ""),
            ("mit", "跟", "with", ""),
            ("ohne", "没有", "without", ""),
            ("für", "为了", "for", ""),
            ("weil", "因为", "because", ""),
            ("dass", "从句连词", "that (conjunction)", ""),
            ("auch", "也", "also", ""),
            ("nur", "只", "only", ""),
            ("sehr", "非常", "very", ""),
            ("schon", "已经", "already", ""),
            ("noch", "还", "still", ""),
            ("hier", "这里", "here", ""),
            ("dort", "那里", "there", ""),
            ("dann", "然后", "then", ""),
        ],
    },
    {
        "key": "polite", "res": "HAN_POLITE", "tier": "beginner",
        "de": "Sei höflich", "zh": "客气", "en": "Be Polite",
        "accent": "BrilliantRose", "icon": "wave",
        "cards": [
            ("Entschuldigen Sie", "打扰一下", "excuse me", ""),
            ("Nach Ihnen", "您先请", "after you", ""),
            ("Darf ich?", "我可以吗", "may i", ""),
            ("Sehr gern", "非常乐意", "with pleasure", ""),
            ("Bitte schön", "不客气", "you're welcome", ""),
            ("Danke, gleichfalls", "谢谢你也一样", "thanks, likewise", ""),
            ("Es tut mir leid", "对不起", "i'm sorry", ""),
            ("Vielen Dank", "非常感谢", "many thanks", ""),
            ("Nichts zu danken", "不用谢", "don't mention it", ""),
            ("Aber gern", "当然乐意", "of course, gladly", ""),
            ("Würden Sie das machen?", "您愿意做吗", "would you do that", ""),
            ("Wenn Sie erlauben", "如果您允许", "if you permit", ""),
        ],
    },
    {
        "key": "counting", "res": "HAN_COUNTING", "tier": "beginner",
        "de": "Zählen", "zh": "序数", "en": "Counting",
        "accent": "Orange", "icon": "num",
        "cards": [
            ("erste", "第一", "first", ""),
            ("zweite", "第二", "second", ""),
            ("dritte", "第三", "third", ""),
            ("vierte", "第四", "fourth", ""),
            ("fünfte", "第五", "fifth", ""),
            ("letzte", "最后", "last", ""),
            ("das Paar", "一对", "pair", "n"),
            ("das Dutzend", "一打", "dozen", "n"),
            ("halb", "半", "half", ""),
            ("die Hälfte", "一半", "half", "f"),
            ("das Viertel", "四分之一", "quarter", "n"),
            ("doppelt", "双倍", "double", ""),
            ("einmal", "一次", "once", ""),
            ("zweimal", "两次", "twice", ""),
            ("dreimal", "三次", "three times", ""),
            ("mehrmals", "多次", "several times", ""),
        ],
    },
    {
        "key": "family2", "res": "HAN_FAMILY2", "tier": "beginner",
        "de": "Familie", "zh": "家庭", "en": "Family",
        "accent": "Folly", "icon": "people",
        "cards": [
            ("die Grossmutter", "祖母", "grandmother", "f"),
            ("der Grossvater", "祖父", "grandfather", "m"),
            ("die Tante", "姑姑", "aunt", "f"),
            ("der Onkel", "叔叔", "uncle", "m"),
            ("die Cousine", "表姐", "female cousin", "f"),
            ("der Cousin", "表哥", "male cousin", "m"),
            ("die Enkelin", "孙女", "granddaughter", "f"),
            ("der Enkel", "孙子", "grandson", "m"),
            ("die Nichte", "侄女", "niece", "f"),
            ("der Neffe", "侄子", "nephew", "m"),
            ("die Eltern", "父母", "parents", "f"),
            ("die Geschwister", "兄弟姐妹", "siblings", "f"),
            ("die Grosseltern", "祖父母", "grandparents", "f"),
            ("der Schwager", "姐夫", "brother-in-law", "m"),
            ("die Schwiegermutter", "婆婆", "mother-in-law", "f"),
            ("das Enkelkind", "孙辈", "grandchild", "n"),
        ],
    },
    {
        "key": "fruit", "res": "HAN_FRUIT", "tier": "elementary",
        "de": "Obst", "zh": "水果", "en": "Fruits",
        "accent": "ChromeYellow", "icon": "cup",
        "cards": [
            ("die Banane", "香蕉", "banana", "f"),
            ("die Birne", "梨", "pear", "f"),
            ("die Traube", "葡萄", "grape", "f"),
            ("die Erdbeere", "草莓", "strawberry", "f"),
            ("die Kirsche", "樱桃", "cherry", "f"),
            ("die Zitrone", "柠檬", "lemon", "f"),
            ("die Orange", "橙子", "orange", "f"),
            ("die Melone", "甜瓜", "melon", "f"),
            ("der Pfirsich", "桃子", "peach", "m"),
            ("die Ananas", "菠萝", "pineapple", "f"),
            ("die Pflaume", "李子", "plum", "f"),
            ("die Himbeere", "树莓", "raspberry", "f"),
            ("die Mango", "芒果", "mango", "f"),
            ("die Kiwi", "猕猴桃", "kiwi", "f"),
            ("die Feige", "无花果", "fig", "f"),
            ("die Grapefruit", "西柚", "grapefruit", "f"),
        ],
    },
    {
        "key": "veg", "res": "HAN_VEG", "tier": "elementary",
        "de": "Gemüse", "zh": "蔬菜", "en": "Vegetables",
        "accent": "SpringBud", "icon": "leaf",
        "cards": [
            ("die Karotte", "胡萝卜", "carrot", "f"),
            ("die Kartoffel", "土豆", "potato", "f"),
            ("die Zwiebel", "洋葱", "onion", "f"),
            ("die Tomate", "西红柿", "tomato", "f"),
            ("die Gurke", "黄瓜", "cucumber", "f"),
            ("der Salat", "生菜", "lettuce", "m"),
            ("der Pilz", "蘑菇", "mushroom", "m"),
            ("der Kohl", "卷心菜", "cabbage", "m"),
            ("die Bohne", "豆子", "bean", "f"),
            ("die Erbse", "豌豆", "pea", "f"),
            ("der Spinat", "菠菜", "spinach", "m"),
            ("der Knoblauch", "大蒜", "garlic", "m"),
            ("der Brokkoli", "西兰花", "broccoli", "m"),
            ("der Mais", "玉米", "corn", "m"),
            ("der Kürbis", "南瓜", "pumpkin", "m"),
            ("der Paprika", "甜椒", "bell pepper", "m"),
        ],
    },
    {
        "key": "drink", "res": "HAN_DRINK", "tier": "elementary",
        "de": "Getränke", "zh": "饮料", "en": "Drinks",
        "accent": "PictonBlue", "icon": "cup",
        "cards": [
            ("der Saft", "果汁", "juice", "m"),
            ("die Limonade", "柠檬汽水", "lemonade", "f"),
            ("der Wein", "葡萄酒", "wine", "m"),
            ("die Cola", "可乐", "cola", "f"),
            ("der Sekt", "起泡酒", "sparkling wine", "m"),
            ("das Mineralwasser", "矿泉水", "mineral water", "n"),
            ("der Orangensaft", "橙汁", "orange juice", "m"),
            ("der Kakao", "可可", "cocoa", "m"),
            ("der Eistee", "冰茶", "iced tea", "m"),
            ("der Cocktail", "鸡尾酒", "cocktail", "m"),
            ("der Smoothie", "果昔", "smoothie", "m"),
            ("die Schorle", "果汁气泡水", "spritzer", "f"),
            ("der Champagner", "香槟", "champagne", "m"),
            ("die heisse Schokolade", "热巧克力", "hot chocolate", "f"),
        ],
    },
    {
        "key": "job", "res": "HAN_JOB", "tier": "elementary",
        "de": "Berufe", "zh": "职业", "en": "Jobs",
        "accent": "Rajah", "icon": "people",
        "cards": [
            ("der Bäcker", "面包师", "baker", "m"),
            ("der Koch", "厨师", "cook", "m"),
            ("der Polizist", "警察", "police officer", "m"),
            ("die Krankenschwester", "护士", "nurse", "f"),
            ("der Feuerwehrmann", "消防员", "firefighter", "m"),
            ("der Verkäufer", "售货员", "salesman", "m"),
            ("der Fahrer", "司机", "driver", "m"),
            ("der Bauer", "农民", "farmer", "m"),
            ("der Maler", "画家", "painter", "m"),
            ("der Musiker", "音乐家", "musician", "m"),
            ("der Pilot", "飞行员", "pilot", "m"),
            ("der Ingenieur", "工程师", "engineer", "m"),
            ("der Anwalt", "律师", "lawyer", "m"),
            ("der Friseur", "理发师", "hairdresser", "m"),
            ("der Briefträger", "邮递员", "postman", "m"),
            ("die Sekretärin", "秘书", "secretary", "f"),
        ],
    },
    {
        "key": "subject", "res": "HAN_SUBJECT", "tier": "elementary",
        "de": "Schulfächer", "zh": "科目", "en": "School Subjects",
        "accent": "KellyGreen", "icon": "book",
        "cards": [
            ("die Mathematik", "数学", "mathematics", "f"),
            ("die Biologie", "生物", "biology", "f"),
            ("die Chemie", "化学", "chemistry", "f"),
            ("die Physik", "物理", "physics", "f"),
            ("die Geschichte", "历史", "history", "f"),
            ("die Erdkunde", "地理", "geography", "f"),
            ("die Kunst", "美术", "art", "f"),
            ("die Note", "分数", "grade", "f"),
            ("die Prüfung", "考试", "exam", "f"),
            ("die Hausaufgabe", "家庭作业", "homework", "f"),
            ("die Pause", "课间休息", "break", "f"),
            ("das Fach", "科目", "subject", "n"),
            ("die Klasse", "班级", "class", "f"),
            ("das Zeugnis", "成绩单", "report card", "n"),
        ],
    },
    {
        "key": "music", "res": "HAN_MUSIC", "tier": "elementary",
        "de": "Instrumente", "zh": "乐器", "en": "Instruments",
        "accent": "Magenta", "icon": "palette",
        "cards": [
            ("die Gitarre", "吉他", "guitar", "f"),
            ("die Geige", "小提琴", "violin", "f"),
            ("die Trommel", "鼓", "drum", "f"),
            ("die Flöte", "长笛", "flute", "f"),
            ("die Trompete", "小号", "trumpet", "f"),
            ("das Cello", "大提琴", "cello", "n"),
            ("das Schlagzeug", "架子鼓", "drum kit", "n"),
            ("die Harfe", "竖琴", "harp", "f"),
            ("die Klarinette", "单簧管", "clarinet", "f"),
            ("das Saxofon", "萨克斯", "saxophone", "n"),
            ("die Blockflöte", "竖笛", "recorder", "f"),
            ("das Akkordeon", "手风琴", "accordion", "n"),
            ("die Mundharmonika", "口琴", "harmonica", "f"),
            ("das Klavier", "钢琴", "piano", "n"),
        ],
    },
    {
        "key": "sportart", "res": "HAN_SPORTART", "tier": "elementary",
        "de": "Sportarten", "zh": "体育", "en": "Sports",
        "accent": "Green", "icon": "ball",
        "cards": [
            ("das Tennis", "网球", "tennis", "n"),
            ("der Volleyball", "排球", "volleyball", "m"),
            ("das Golf", "高尔夫球", "golf", "n"),
            ("das Boxen", "拳击", "boxing", "n"),
            ("das Skifahren", "滑雪", "skiing", "n"),
            ("das Joggen", "慢跑", "jogging", "n"),
            ("das Turnen", "体操", "gymnastics", "n"),
            ("das Klettern", "攀岩", "climbing", "n"),
            ("das Segeln", "帆船运动", "sailing", "n"),
            ("das Rudern", "划船", "rowing", "n"),
            ("das Yoga", "瑜伽", "yoga", "n"),
            ("der Handball", "手球", "handball", "m"),
            ("das Tischtennis", "乒乓球", "table tennis", "n"),
            ("das Schwimmen", "游泳", "swimming", "n"),
            ("das Reiten", "骑马", "horse riding", "n"),
            ("der Marathon", "马拉松", "marathon", "m"),
        ],
    },
    {
        "key": "garden", "res": "HAN_GARDEN", "tier": "elementary",
        "de": "Im Garten", "zh": "花园", "en": "In the Garden",
        "accent": "KellyGreen", "icon": "leaf",
        "cards": [
            ("die Blume", "花", "flower", "f"),
            ("der Baum", "树", "tree", "m"),
            ("die Rose", "玫瑰", "rose", "f"),
            ("der Zaun", "栅栏", "fence", "m"),
            ("der Rasen", "草坪", "lawn", "m"),
            ("das Blatt", "叶子", "leaf", "n"),
            ("die Wurzel", "根", "root", "f"),
            ("der Ast", "树枝", "branch", "m"),
            ("der Busch", "灌木", "bush", "m"),
            ("die Tulpe", "郁金香", "tulip", "f"),
            ("das Beet", "花坛", "flower bed", "n"),
            ("die Giesskanne", "浇水壶", "watering can", "f"),
            ("der Samen", "种子", "seed", "m"),
            ("die Hecke", "树篱", "hedge", "f"),
        ],
    },
    {
        "key": "shape", "res": "HAN_SHAPE", "tier": "elementary",
        "de": "Formen", "zh": "形状", "en": "Shapes",
        "accent": "Cyan", "icon": "box",
        "cards": [
            ("der Kreis", "圆形", "circle", "m"),
            ("das Quadrat", "正方形", "square", "n"),
            ("das Dreieck", "三角形", "triangle", "n"),
            ("das Rechteck", "长方形", "rectangle", "n"),
            ("das Oval", "椭圆形", "oval", "n"),
            ("die Linie", "线条", "line", "f"),
            ("der Punkt", "点", "point", "m"),
            ("die Kurve", "曲线", "curve", "f"),
            ("der Würfel", "立方体", "cube", "m"),
            ("die Kugel", "球体", "sphere", "f"),
            ("der Ring", "圆环", "ring", "m"),
            ("die Ecke", "角", "corner", "f"),
        ],
    },
    {
        "key": "bath", "res": "HAN_BATH", "tier": "elementary",
        "de": "Im Bad", "zh": "浴室", "en": "In the Bathroom",
        "accent": "PictonBlue", "icon": "house",
        "cards": [
            ("die Seife", "肥皂", "soap", "f"),
            ("das Handtuch", "毛巾", "towel", "n"),
            ("die Zahnbürste", "牙刷", "toothbrush", "f"),
            ("die Zahnpasta", "牙膏", "toothpaste", "f"),
            ("die Dusche", "淋浴", "shower", "f"),
            ("die Badewanne", "浴缸", "bathtub", "f"),
            ("der Spiegel", "镜子", "mirror", "m"),
            ("der Kamm", "梳子", "comb", "m"),
            ("das Shampoo", "洗发水", "shampoo", "n"),
            ("das Waschbecken", "洗脸盆", "sink", "n"),
            ("der Föhn", "吹风机", "hairdryer", "m"),
            ("die Bürste", "刷子", "brush", "f"),
            ("das Klopapier", "卫生纸", "toilet paper", "n"),
            ("der Rasierer", "剃须刀", "razor", "m"),
        ],
    },
    {
        "key": "birthday", "res": "HAN_BIRTHDAY", "tier": "elementary",
        "de": "Geburtstag", "zh": "生日", "en": "Birthday",
        "accent": "BrilliantRose", "icon": "heart",
        "cards": [
            ("der Kuchen", "蛋糕", "cake", "m"),
            ("die Kerze", "蜡烛", "candle", "f"),
            ("das Geschenk", "礼物", "gift", "n"),
            ("der Luftballon", "气球", "balloon", "m"),
            ("die Überraschung", "惊喜", "surprise", "f"),
            ("die Einladung", "邀请函", "invitation", "f"),
            ("die Girlande", "花环", "garland", "f"),
            ("die Feier", "庆祝活动", "celebration", "f"),
            ("der Gast", "客人", "guest", "m"),
            ("das Fest", "节日", "festival", "n"),
            ("der Wunsch", "愿望", "wish", "m"),
            ("das Konfetti", "五彩纸屑", "confetti", "n"),
            ("die Geburtstagskarte", "生日贺卡", "birthday card", "f"),
            ("das Ständchen", "小夜曲", "serenade", "n"),
        ],
    },
    {
        "key": "bakery", "res": "HAN_BAKERY", "tier": "elementary",
        "de": "Beim Bäcker", "zh": "烘焙", "en": "At the Bakery",
        "accent": "Orange", "icon": "cup",
        "cards": [
            ("das Brötchen", "小面包", "bread roll", "n"),
            ("das Croissant", "牛角面包", "croissant", "n"),
            ("die Brezel", "德式扭结面包", "pretzel", "f"),
            ("der Keks", "饼干", "cookie", "m"),
            ("der Donut", "甜甜圈", "donut", "m"),
            ("die Semmel", "小圆面包", "bread roll", "f"),
            ("das Baguette", "法棍面包", "baguette", "n"),
            ("der Zopf", "辫子面包", "braided bread", "m"),
            ("das Vollkornbrot", "全麦面包", "whole grain bread", "n"),
            ("die Waffel", "华夫饼", "waffle", "f"),
            ("der Muffin", "玛芬蛋糕", "muffin", "m"),
            ("der Pfannkuchen", "薄煎饼", "pancake", "m"),
            ("die Torte", "奶油蛋糕", "layer cake", "f"),
            ("das Gebäck", "糕点", "pastry", "n"),
        ],
    },
    {
        "key": "body2", "res": "HAN_BODY2", "tier": "elementary",
        "de": "Körper 2", "zh": "身体", "en": "Body 2",
        "accent": "Folly", "icon": "people",
        "cards": [
            ("die Haut", "皮肤", "skin", "f"),
            ("der Knochen", "骨头", "bone", "m"),
            ("das Blut", "血液", "blood", "n"),
            ("das Gehirn", "大脑", "brain", "n"),
            ("die Lunge", "肺", "lung", "f"),
            ("der Magen", "胃", "stomach", "m"),
            ("die Leber", "肝脏", "liver", "f"),
            ("die Niere", "肾脏", "kidney", "f"),
            ("der Muskel", "肌肉", "muscle", "m"),
            ("die Ader", "血管", "vein", "f"),
            ("der Nagel", "指甲", "nail", "m"),
            ("die Wimper", "睫毛", "eyelash", "f"),
            ("die Lippe", "嘴唇", "lip", "f"),
            ("die Wange", "脸颊", "cheek", "f"),
            ("das Kinn", "下巴", "chin", "n"),
            ("die Stirn", "额头", "forehead", "f"),
        ],
    },
    {
        "key": "nature", "res": "HAN_NATURE", "tier": "intermediate",
        "de": "Landschaft", "zh": "风景", "en": "Landscape",
        "accent": "Green", "icon": "leaf",
        "cards": [
            ("der Berg", "山", "mountain", "m"),
            ("der Fluss", "河流", "river", "m"),
            ("der See", "湖", "lake", "m"),
            ("das Meer", "海", "sea", "n"),
            ("das Tal", "山谷", "valley", "n"),
            ("der Hügel", "小山", "hill", "m"),
            ("die Höhle", "洞穴", "cave", "f"),
            ("der Wasserfall", "瀑布", "waterfall", "m"),
            ("die Wüste", "沙漠", "desert", "f"),
            ("der Vulkan", "火山", "volcano", "m"),
            ("die Klippe", "悬崖", "cliff", "f"),
            ("der Bach", "小溪", "stream", "m"),
            ("die Wiese", "草地", "meadow", "f"),
            ("der Gipfel", "山顶", "summit", "m"),
            ("die Quelle", "泉水", "spring", "f"),
            ("der Teich", "池塘", "pond", "m"),
        ],
    },
    {
        "key": "direction", "res": "HAN_DIRECTION", "tier": "intermediate",
        "de": "Der Weg", "zh": "方向", "en": "Directions",
        "accent": "VividCerulean", "icon": "plane",
        "cards": [
            ("Wie komme ich zum Bahnhof?", "怎么去火车站", "how do i get to the station", ""),
            ("Gehen Sie geradeaus", "一直往前走", "go straight ahead", ""),
            ("Biegen Sie links ab", "向左转", "turn left", ""),
            ("Biegen Sie rechts ab", "向右转", "turn right", ""),
            ("Es ist um die Ecke", "就在拐角处", "it's around the corner", ""),
            ("An der nächsten Ampel", "在下一个红绿灯", "at the next traffic light", ""),
            ("Neben der Bank", "在银行旁边", "next to the bank", ""),
            ("Wie weit ist es?", "有多远", "how far is it", ""),
            ("Ganz in der Nähe", "就在附近", "very close by", ""),
            ("Auf der linken Seite", "在左边", "on the left side", ""),
            ("Zwei Strassen weiter", "再过两条街", "two streets further", ""),
            ("Direkt gegenüber", "正对面", "directly opposite", ""),
        ],
    },
    {
        "key": "character", "res": "HAN_CHARACTER", "tier": "intermediate",
        "de": "Charakter", "zh": "性格", "en": "Personality",
        "accent": "Purple", "icon": "people",
        "cards": [
            ("freundlich", "友好的", "friendly", ""),
            ("nett", "亲切的", "nice", ""),
            ("höflich", "有礼貌的", "polite", ""),
            ("ehrlich", "诚实的", "honest", ""),
            ("fleissig", "勤奋的", "hardworking", ""),
            ("faul", "懒惰的", "lazy", ""),
            ("klug", "聪明的", "clever", ""),
            ("dumm", "愚蠢的", "stupid", ""),
            ("mutig", "勇敢的", "brave", ""),
            ("schüchtern", "害羞的", "shy", ""),
            ("geduldig", "有耐心的", "patient", ""),
            ("grosszügig", "慷慨的", "generous", ""),
            ("ruhig", "安静的", "calm", ""),
            ("lustig", "有趣的", "funny", ""),
            ("ernst", "严肃的", "serious", ""),
            ("streng", "严格的", "strict", ""),
        ],
    },
    {
        "key": "environ", "res": "HAN_ENVIRON", "tier": "intermediate",
        "de": "Umwelt", "zh": "环境", "en": "Environment",
        "accent": "KellyGreen", "icon": "leaf",
        "cards": [
            ("die Umwelt", "环境", "environment", "f"),
            ("der Müll", "垃圾", "garbage", "m"),
            ("das Recycling", "回收", "recycling", "n"),
            ("die Energie", "能源", "energy", "f"),
            ("das Klima", "气候", "climate", "n"),
            ("die Verschmutzung", "污染", "pollution", "f"),
            ("der Klimawandel", "气候变化", "climate change", "m"),
            ("das Plastik", "塑料", "plastic", "n"),
            ("der Strom", "电", "electricity", "m"),
            ("die Solarzelle", "太阳能电池", "solar cell", "f"),
            ("der Abfall", "废物", "waste", "m"),
            ("die Windkraft", "风能", "wind power", "f"),
            ("der Umweltschutz", "环境保护", "environmental protection", "m"),
            ("die Erderwärmung", "全球变暖", "global warming", "f"),
        ],
    },
    {
        "key": "hotel", "res": "HAN_HOTEL", "tier": "intermediate",
        "de": "Im Hotel", "zh": "酒店", "en": "At the Hotel",
        "accent": "Rajah", "icon": "house",
        "cards": [
            ("das Einzelzimmer", "单人间", "single room", "n"),
            ("das Doppelzimmer", "双人间", "double room", "n"),
            ("die Rezeption", "前台", "reception", "f"),
            ("die Reservierung", "预订", "reservation", "f"),
            ("das Gepäck", "行李", "luggage", "n"),
            ("der Aufzug", "电梯", "elevator", "m"),
            ("das Frühstück", "早餐", "breakfast", "n"),
            ("die Übernachtung", "住一晚", "overnight stay", "f"),
            ("der Zimmerservice", "客房服务", "room service", "m"),
            ("die Minibar", "迷你吧", "minibar", "f"),
            ("Ich habe reserviert", "我预订了", "i have a reservation", ""),
            ("Haben Sie ein Zimmer frei?", "你们有空房吗", "do you have a room available", ""),
        ],
    },
    {
        "key": "airport", "res": "HAN_AIRPORT", "tier": "intermediate",
        "de": "Am Flughafen", "zh": "机场", "en": "At the Airport",
        "accent": "PictonBlue", "icon": "plane",
        "cards": [
            ("das Gate", "登机口", "gate", "n"),
            ("der Koffer", "行李箱", "suitcase", "m"),
            ("die Bordkarte", "登机牌", "boarding pass", "f"),
            ("der Abflug", "起飞", "departure", "m"),
            ("die Ankunft", "到达", "arrival", "f"),
            ("das Handgepäck", "手提行李", "hand luggage", "n"),
            ("der Zoll", "海关", "customs", "m"),
            ("die Sicherheitskontrolle", "安检", "security check", "f"),
            ("der Flug", "航班", "flight", "m"),
            ("die Verspätung", "延误", "delay", "f"),
            ("die Landung", "降落", "landing", "f"),
            ("der Passagier", "乘客", "passenger", "m"),
            ("die Fluglinie", "航空公司", "airline", "f"),
            ("der Notausgang", "紧急出口", "emergency exit", "m"),
        ],
    },
    {
        "key": "money", "res": "HAN_MONEY", "tier": "intermediate",
        "de": "Bank & Geld", "zh": "银行", "en": "Bank & Money",
        "accent": "MintGreen", "icon": "bag",
        "cards": [
            ("das Konto", "账户", "account", "n"),
            ("die Kreditkarte", "信用卡", "credit card", "f"),
            ("die Münze", "硬币", "coin", "f"),
            ("der Schein", "纸币", "banknote", "m"),
            ("das Bargeld", "现金", "cash", "n"),
            ("die Überweisung", "转账", "bank transfer", "f"),
            ("der Geldautomat", "自动取款机", "cash machine", "m"),
            ("die Zinsen", "利息", "interest", "f"),
            ("das Wechselgeld", "找零", "change", "n"),
            ("die Währung", "货币", "currency", "f"),
            ("der Kredit", "贷款", "loan", "m"),
            ("die Gebühr", "费用", "fee", "f"),
            ("das Portemonnaie", "钱包", "wallet", "n"),
            ("das Sparbuch", "存折", "savings book", "n"),
        ],
    },
    {
        "key": "chore", "res": "HAN_CHORE", "tier": "intermediate",
        "de": "Hausarbeit", "zh": "家务", "en": "Housework",
        "accent": "Orange", "icon": "house",
        "cards": [
            ("putzen", "打扫", "to clean", ""),
            ("waschen", "洗", "to wash", ""),
            ("aufräumen", "收拾", "to tidy up", ""),
            ("bügeln", "熨烫", "to iron", ""),
            ("staubsaugen", "吸尘", "to vacuum", ""),
            ("abwaschen", "洗碗", "to do the dishes", ""),
            ("wischen", "擦", "to wipe", ""),
            ("die Wäsche", "要洗的衣物", "laundry", "f"),
            ("der Besen", "扫帚", "broom", "m"),
            ("der Staubsauger", "吸尘器", "vacuum cleaner", "m"),
            ("der Eimer", "水桶", "bucket", "m"),
            ("der Lappen", "抹布", "rag", "m"),
            ("der Schwamm", "海绵", "sponge", "m"),
            ("aufhängen", "挂起", "to hang up", ""),
        ],
    },
    {
        "key": "media", "res": "HAN_MEDIA", "tier": "intermediate",
        "de": "Medien", "zh": "媒体", "en": "Media",
        "accent": "VividCerulean", "icon": "phone",
        "cards": [
            ("die Zeitung", "报纸", "newspaper", "f"),
            ("das Radio", "收音机", "radio", "n"),
            ("die Nachrichten", "新闻", "the news", "f"),
            ("die Sendung", "节目", "broadcast", "f"),
            ("der Sender", "电视台", "broadcasting station", "m"),
            ("die Werbung", "广告", "advertising", "f"),
            ("der Kanal", "频道", "channel", "m"),
            ("die Schlagzeile", "头条", "headline", "f"),
            ("der Journalist", "记者", "journalist", "m"),
            ("das Interview", "采访", "interview", "n"),
            ("der Podcast", "播客", "podcast", "m"),
            ("das Abo", "订阅", "subscription", "n"),
            ("die Reportage", "报道", "report", "f"),
            ("der Zuschauer", "观众", "viewer", "m"),
        ],
    },
    {
        "key": "weather2", "res": "HAN_WEATHER2", "tier": "intermediate",
        "de": "Wetter 2", "zh": "气候", "en": "Weather 2",
        "accent": "PictonBlue", "icon": "cloud",
        "cards": [
            ("der Sturm", "风暴", "storm", "m"),
            ("das Gewitter", "雷雨", "thunderstorm", "n"),
            ("der Blitz", "闪电", "lightning", "m"),
            ("der Donner", "雷声", "thunder", "m"),
            ("der Hagel", "冰雹", "hail", "m"),
            ("der Frost", "霜冻", "frost", "m"),
            ("der Tau", "露水", "dew", "m"),
            ("die Hitze", "炎热", "heat", "f"),
            ("die Kälte", "寒冷", "cold", "f"),
            ("der Regenbogen", "彩虹", "rainbow", "m"),
            ("die Überschwemmung", "洪水", "flood", "f"),
            ("die Dürre", "干旱", "drought", "f"),
            ("der Schauer", "阵雨", "shower", "m"),
            ("die Brise", "微风", "breeze", "f"),
            ("bewölkt", "多云的", "cloudy", ""),
            ("neblig", "有雾的", "foggy", ""),
        ],
    },
    {
        "key": "describe", "res": "HAN_DESCRIBE", "tier": "intermediate",
        "de": "Beschreiben", "zh": "描述", "en": "Describing",
        "accent": "Magenta", "icon": "palette",
        "cards": [
            ("rund", "圆的", "round", ""),
            ("eckig", "有棱角的", "angular", ""),
            ("weich", "软的", "soft", ""),
            ("hart", "硬的", "hard", ""),
            ("glatt", "光滑的", "smooth", ""),
            ("rau", "粗糙的", "rough", ""),
            ("scharf", "锋利的", "sharp", ""),
            ("stumpf", "钝的", "blunt", ""),
            ("sauber", "干净的", "clean", ""),
            ("schmutzig", "脏的", "dirty", ""),
            ("frisch", "新鲜的", "fresh", ""),
            ("modern", "现代的", "modern", ""),
            ("altmodisch", "老式的", "old-fashioned", ""),
            ("breit", "宽的", "wide", ""),
            ("schmal", "窄的", "narrow", ""),
            ("flach", "平的", "flat", ""),
        ],
    },
    {
        "key": "quantity", "res": "HAN_QUANTITY", "tier": "intermediate",
        "de": "Mengen", "zh": "数量", "en": "Quantities",
        "accent": "Cyan", "icon": "num",
        "cards": [
            ("das Kilo", "公斤", "kilo", "n"),
            ("das Gramm", "克", "gram", "n"),
            ("der Liter", "升", "liter", "m"),
            ("das Stück", "块", "piece", "n"),
            ("die Flasche", "瓶", "bottle", "f"),
            ("die Dose", "罐头", "can", "f"),
            ("die Packung", "包", "pack", "f"),
            ("die Scheibe", "片", "slice", "f"),
            ("die Tüte", "袋子", "bag", "f"),
            ("die Portion", "份", "portion", "f"),
            ("die Menge", "数量", "quantity", "f"),
            ("das Paket", "包裹", "parcel", "n"),
            ("ein bisschen", "一点儿", "a little", ""),
            ("genug", "足够", "enough", ""),
            ("mehr", "更多", "more", ""),
            ("weniger", "更少", "less", ""),
        ],
    },
    {
        "key": "feel2", "res": "HAN_FEEL2", "tier": "intermediate",
        "de": "Gefühle 2", "zh": "情绪", "en": "Feelings 2",
        "accent": "BrilliantRose", "icon": "heart",
        "cards": [
            ("aufgeregt", "兴奋的", "excited", ""),
            ("enttäuscht", "失望的", "disappointed", ""),
            ("stolz", "自豪的", "proud", ""),
            ("eifersüchtig", "嫉妒的", "jealous", ""),
            ("überrascht", "惊讶的", "surprised", ""),
            ("verliebt", "恋爱中的", "in love", ""),
            ("einsam", "孤独的", "lonely", ""),
            ("ängstlich", "焦虑的", "anxious", ""),
            ("gelangweilt", "无聊的", "bored", ""),
            ("zufrieden", "满意的", "satisfied", ""),
            ("dankbar", "感激的", "grateful", ""),
            ("erschöpft", "筋疲力尽的", "exhausted", ""),
            ("verwirrt", "困惑的", "confused", ""),
            ("begeistert", "热情洋溢的", "enthusiastic", ""),
            ("besorgt", "担忧的", "worried", ""),
            ("nervös", "紧张的", "nervous", ""),
        ],
    },
    {
        "key": "adverb", "res": "HAN_ADVERB", "tier": "intermediate",
        "de": "Oft & Selten", "zh": "频率", "en": "Frequency",
        "accent": "MintGreen", "icon": "clock",
        "cards": [
            ("oft", "经常", "often", ""),
            ("selten", "很少", "rarely", ""),
            ("manchmal", "有时", "sometimes", ""),
            ("meistens", "大多数时候", "mostly", ""),
            ("täglich", "每天", "daily", ""),
            ("wöchentlich", "每周", "weekly", ""),
            ("monatlich", "每月", "monthly", ""),
            ("jährlich", "每年", "yearly", ""),
            ("bald", "很快", "soon", ""),
            ("sofort", "立刻", "immediately", ""),
            ("gleich", "马上", "right away", ""),
            ("gerade", "刚才", "just now", ""),
            ("endlich", "终于", "finally", ""),
            ("plötzlich", "突然", "suddenly", ""),
            ("immer wieder", "一再", "again and again", ""),
            ("ab und zu", "偶尔", "now and then", ""),
        ],
    },
    {
        "key": "interview", "res": "HAN_INTERVIEW", "tier": "advanced",
        "de": "Bewerbung", "zh": "求职", "en": "Job Interview",
        "accent": "KellyGreen", "icon": "book",
        "cards": [
            ("Ich suche eine Stelle", "我在找工作", "i'm looking for a job", ""),
            ("Ich habe Erfahrung", "我有经验", "i have experience", ""),
            ("Was sind Ihre Stärken?", "您的优势是什么", "what are your strengths", ""),
            ("Ich bin teamfähig", "我善于团队合作", "i'm a team player", ""),
            ("Wann kann ich anfangen?", "我什么时候可以开始", "when can i start", ""),
            ("Wie ist das Gehalt?", "工资是多少", "what's the salary", ""),
            ("Ich bewerbe mich", "我来应聘", "i'm applying", ""),
            ("Ich habe studiert", "我上过大学", "i studied at university", ""),
            ("der Lebenslauf", "简历", "cv", "m"),
            ("das Vorstellungsgespräch", "面试", "job interview", "n"),
            ("die Stelle", "职位", "position", "f"),
            ("die Erfahrung", "经验", "experience", "f"),
            ("die Bewerbung", "求职申请", "job application", "f"),
        ],
    },
    {
        "key": "telefon", "res": "HAN_TELEFON", "tier": "advanced",
        "de": "Am Telefon", "zh": "电话", "en": "On the Phone",
        "accent": "VividCerulean", "icon": "phone",
        "cards": [
            ("Wer ist am Apparat?", "您是哪位", "who is speaking", ""),
            ("Kann ich mit Anna sprechen?", "我可以和安娜通话吗", "can i speak with anna", ""),
            ("Ich rufe später zurück", "我稍后回电", "i'll call back later", ""),
            ("Die Leitung ist besetzt", "电话占线", "the line is busy", ""),
            ("Ich verbinde Sie", "我为您转接", "i'll connect you", ""),
            ("Auf Wiederhören", "再见", "goodbye (on the phone)", ""),
            ("Ich habe mich verwählt", "我拨错号了", "i dialed the wrong number", ""),
            ("Bleiben Sie dran", "请别挂断", "stay on the line", ""),
            ("Können Sie mich hören?", "您能听到我吗", "can you hear me", ""),
            ("Ist Herr Meier da?", "迈尔先生在吗", "is mr. meier there", ""),
            ("Einen Augenblick bitte", "请稍等", "one moment please", ""),
            ("Ich hinterlasse eine Nachricht", "我留个言", "i'll leave a message", ""),
        ],
    },
    {
        "key": "appointment", "res": "HAN_APPOINTMENT", "tier": "advanced",
        "de": "Termine", "zh": "约会", "en": "Appointments",
        "accent": "Orange", "icon": "calendar",
        "cards": [
            ("Ich möchte einen Termin", "我想预约", "i'd like an appointment", ""),
            ("Haben Sie am Montag Zeit?", "您周一有时间吗", "do you have time on monday", ""),
            ("Passt Ihnen Dienstag?", "周二您方便吗", "does tuesday suit you", ""),
            ("Um wie viel Uhr?", "几点", "at what time", ""),
            ("Ich muss absagen", "我得取消", "i have to cancel", ""),
            ("Können wir verschieben?", "我们能改期吗", "can we reschedule", ""),
            ("Bis nächste Woche", "下周见", "see you next week", ""),
            ("Ich bin verhindert", "我来不了", "i'm unavailable", ""),
            ("Wann treffen wir uns?", "我们什么时候见", "when do we meet", ""),
            ("Ich komme etwas später", "我会晚点到", "i'll come a bit later", ""),
            ("Pünktlich um acht", "八点准时", "punctually at eight", ""),
            ("Der Termin passt mir", "这个时间我可以", "the appointment suits me", ""),
        ],
    },
    {
        "key": "complaint", "res": "HAN_COMPLAINT", "tier": "advanced",
        "de": "Beschwerden", "zh": "投诉", "en": "Complaints",
        "accent": "Red", "icon": "warning",
        "cards": [
            ("Das ist nicht richtig", "这不对", "that's not right", ""),
            ("Ich möchte mich beschweren", "我想投诉", "to complain", ""),
            ("Das funktioniert nicht", "这个不管用", "it doesn't work", ""),
            ("Ich will mein Geld zurück", "我要退款", "i want my money back", ""),
            ("Das ist zu teuer", "这太贵了", "that's too expensive", ""),
            ("Ich bin nicht zufrieden", "我不满意", "i'm not satisfied", ""),
            ("Das ist kaputt", "这坏了", "it's broken", ""),
            ("Ich warte schon lange", "我等很久了", "i've been waiting a long time", ""),
            ("Das habe ich nicht bestellt", "我没点这个", "i didn't order this", ""),
            ("Wo ist der Chef?", "老板在哪里", "where's the boss", ""),
            ("Das ist inakzeptabel", "这不可接受", "that's unacceptable", ""),
            ("Können Sie das umtauschen?", "您能换货吗", "can you exchange this", ""),
        ],
    },
    {
        "key": "smalltalk", "res": "HAN_SMALLTALK", "tier": "advanced",
        "de": "Small Talk", "zh": "闲聊", "en": "Small Talk",
        "accent": "Magenta", "icon": "speech",
        "cards": [
            ("Schönes Wetter heute", "今天天气真好", "nice weather today", ""),
            ("Was machst du beruflich?", "你做什么工作", "what do you do for work", ""),
            ("Wie war dein Wochenende?", "你周末过得怎么样", "how was your weekend", ""),
            ("Was machst du gern?", "你喜欢做什么", "what do you like to do", ""),
            ("Hast du Geschwister?", "你有兄弟姐妹吗", "do you have siblings", ""),
            ("Bist du zum ersten Mal hier?", "你第一次来这里吗", "is this your first time here", ""),
            ("Was für Musik magst du?", "你喜欢什么音乐", "what music do you like", ""),
            ("Machst du oft Sport?", "你经常运动吗", "do you often play sports", ""),
            ("Wir sehen uns", "回头见", "see you", ""),
            ("Wie gefällt dir die Stadt?", "你觉得这个城市怎么样", "how do you like the city", ""),
            ("Hast du Urlaub?", "你在休假吗", "are you on vacation", ""),
            ("Schön, dich zu sehen", "很高兴见到你", "nice to see you", ""),
        ],
    },
    {
        "key": "travel2", "res": "HAN_TRAVEL2", "tier": "advanced",
        "de": "Reisen 2", "zh": "旅游", "en": "Travel 2",
        "accent": "Rajah", "icon": "plane",
        "cards": [
            ("Ich möchte ein Zimmer buchen", "我想订一个房间", "i'd like to book a room", ""),
            ("Wann fährt der nächste Zug?", "下一班火车几点开", "when does the next train leave", ""),
            ("Wo kaufe ich Tickets?", "我在哪儿买票", "where do i buy tickets", ""),
            ("Ist dieser Platz frei?", "这个座位有人吗", "is this seat free", ""),
            ("Wie lange dauert die Fahrt?", "车程要多久", "how long is the trip", ""),
            ("Wo ist der Ausgang?", "出口在哪儿", "where is the exit", ""),
            ("Gibt es hier WLAN?", "这里有无线网吗", "is there wifi here", ""),
            ("Können Sie ein Taxi rufen?", "您能叫辆出租车吗", "can you call a taxi", ""),
            ("Wo ist die Information?", "问询处在哪儿", "where is the information desk", ""),
            ("Ich brauche ein Ticket", "我需要一张票", "i need a ticket", ""),
            ("Was kostet die Fahrt?", "车费多少钱", "how much is the fare", ""),
            ("Wo geht es zum Zentrum?", "怎么去市中心", "how do i get to the center", ""),
        ],
    },
    {
        "key": "business", "res": "HAN_BUSINESS", "tier": "advanced",
        "de": "Geschäftlich", "zh": "商务", "en": "Business",
        "accent": "KellyGreen", "icon": "book",
        "cards": [
            ("die Verhandlung", "谈判", "negotiation", "f"),
            ("die Präsentation", "演示", "presentation", "f"),
            ("die Konferenz", "会议", "conference", "f"),
            ("der Umsatz", "营业额", "turnover", "m"),
            ("der Gewinn", "利润", "profit", "m"),
            ("die Strategie", "战略", "strategy", "f"),
            ("der Partner", "合作伙伴", "partner", "m"),
            ("die Firma", "公司", "company", "f"),
            ("die Investition", "投资", "investment", "f"),
            ("der Vorstand", "董事会", "executive board", "m"),
            ("die Abteilung", "部门", "department", "f"),
            ("das Angebot", "报价", "offer", "n"),
            ("die Nachfrage", "需求", "demand", "f"),
            ("der Vertrieb", "销售", "sales", "m"),
        ],
    },
    {
        "key": "abstract", "res": "HAN_ABSTRACT", "tier": "advanced",
        "de": "Ideen", "zh": "观念", "en": "Abstract Ideas",
        "accent": "Purple", "icon": "book",
        "cards": [
            ("die Freiheit", "自由", "freedom", "f"),
            ("die Wahrheit", "真理", "truth", "f"),
            ("die Liebe", "爱", "love", "f"),
            ("die Hoffnung", "希望", "hope", "f"),
            ("der Frieden", "和平", "peace", "m"),
            ("die Gerechtigkeit", "正义", "justice", "f"),
            ("die Macht", "权力", "power", "f"),
            ("das Glück", "幸福", "happiness", "n"),
            ("die Angst", "恐惧", "fear", "f"),
            ("der Traum", "梦", "dream", "m"),
            ("die Erinnerung", "回忆", "memory", "f"),
            ("die Zukunft", "未来", "future", "f"),
            ("die Vergangenheit", "过去", "past", "f"),
            ("der Sinn", "意义", "meaning", "m"),
            ("die Seele", "灵魂", "soul", "f"),
            ("der Mut", "勇气", "courage", "m"),
        ],
    },
]

# ---------------------------------------------------------------------------
# Bilingual UI text. Every Chinese string the C code draws OUTSIDE of a card
# answer must be listed here, so its glyphs land in the always-loaded UI atlas.
# (Deck names and tier names are collected automatically.)
# ---------------------------------------------------------------------------
UI_STRINGS = {
    "TITLE":     "学德语",      # Learn German
    "DE":        "德",                  # "German" tag for the direction chip
    "ZH":        "中",                  # "Chinese" tag for the direction chip
    "FLIP":      "翻",                  # flip
    "DONE":      "完成",            # done / complete
    "LEARNED":   "学会",            # learned
    "AGAIN":     "再来",            # again
    "MENU":      "菜单",            # menu
    "STATS":     "统计",            # statistics
    "WORDS":     "词",                  # words (counter unit)
    "DECKS":     "组",                  # decks/groups (counter unit)
}

# Random praise (shown on a correct answer) and nudges (on a miss).
UI_PRAISE = ["太棒了", "真厉害", "好极了"]   # awesome / impressive / great
UI_NUDGE  = ["差一点", "再试试", "加油"]         # almost / try again / keep going
